---------------------------------------------------------------------------------
--------------------------以下代码为自动生成，请勿手工改动-----------------------
---------------------------------------------------------------------------------


tb_item_template = {
	--  id:int	道具ID
	--  name:string	名称
	--  level:int	限制等级
	--  rank:int	等阶
	--  type:int	子类型
	--  pos:int	装备部位
	--  quality:int	品质
	--  sex:int	性别
	--  price:int	出售价格
	--  is_transaction:int	是否可交易
	--  max_overlap:int	最大堆叠数
	--  is_slather:int	是否可批量使用
	--  use_result:int	使用结果类型
	--  basic_properties:array	基础属性
	--  suit_id:array	套装ID
	--  using_effect:array	使用效果
	--  use_limit:int	每日使用限制
	--  category:int	物品族
	--  category_cooldown:int	族冷却时间（ms）
	--  cooldown:int	使用冷却时间（ms）
	--  is_discard:int	是否可丢弃
	--  goods_id:int	物品不足购买商品ID
	--  expend_data:int	扩展字段
	--  use_object:int	使用对象
	--  quest:int	任务标志
	--  forge_pro:array	装备锻造属性
	--  forge_pro_max:array	装备锻造属性最大范围
	--  is_auction:int	是否可风流镇拍卖
	--  auction_money:int	拍卖底价（元宝）
	[1] = {id = 1,name = "元宝",level = 0,rank = 0,type = 31,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[2] = {id = 2,name = "绑定元宝",level = 0,rank = 0,type = 31,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[3] = {id = 3,name = "银币",level = 0,rank = 0,type = 31,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[4] = {id = 4,name = "绑定银币",level = 0,rank = 0,type = 31,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[5] = {id = 5,name = "声望",level = 0,rank = 0,type = 31,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[6] = {id = 6,name = "荣誉",level = 0,rank = 0,type = 31,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[7] = {id = 7,name = "功勋",level = 0,rank = 0,type = 31,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[8] = {id = 8,name = "家族贡献",level = 0,rank = 0,type = 31,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[9] = {id = 9,name = "经验",level = 0,rank = 0,type = 32,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10] = {id = 10,name = "坐骑经验",level = 0,rank = 0,type = 32,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[11] = {id = 11,name = "侠客经验",level = 0,rank = 0,type = 32,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[12] = {id = 12,name = "宠物经验",level = 0,rank = 0,type = 32,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 41,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[13] = {id = 13,name = "真气",level = 0,rank = 0,type = 32,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[14] = {id = 14,name = "兽灵",level = 0,rank = 0,type = 32,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[15] = {id = 15,name = "宝石精华",level = 0,rank = 0,type = 32,pos = 0,quality = 0,sex = 0,price = 0,is_transaction = 0,max_overlap = 0,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10001] = {id = 10001,name = "一阶武器（男）",level = 1,rank = 1,type = 1,pos = 1,quality = 0,sex = 1,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,35}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10002] = {id = 10002,name = "一阶衣服（男）",level = 1,rank = 1,type = 1,pos = 2,quality = 0,sex = 1,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,23}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10003] = {id = 10003,name = "一阶护手（男）",level = 1,rank = 1,type = 1,pos = 3,quality = 0,sex = 1,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10004] = {id = 10004,name = "一阶腰带（男）",level = 1,rank = 1,type = 1,pos = 4,quality = 0,sex = 1,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,167}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10005] = {id = 10005,name = "一阶鞋子（男）",level = 1,rank = 1,type = 1,pos = 5,quality = 0,sex = 1,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,14}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10006] = {id = 10006,name = "一阶头饰（男）",level = 1,rank = 1,type = 1,pos = 6,quality = 0,sex = 1,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,167}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10007] = {id = 10007,name = "一阶项链（男）",level = 1,rank = 1,type = 1,pos = 7,quality = 0,sex = 1,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10008] = {id = 10008,name = "一阶手镯（男）",level = 1,rank = 1,type = 1,pos = 8,quality = 0,sex = 1,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10009] = {id = 10009,name = "一阶戒指（男）",level = 1,rank = 1,type = 1,pos = 9,quality = 0,sex = 1,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,5}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10010] = {id = 10010,name = "一阶腰坠（男）",level = 1,rank = 1,type = 1,pos = 10,quality = 0,sex = 1,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,3}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10011] = {id = 10011,name = "一阶武器（女）",level = 1,rank = 1,type = 1,pos = 1,quality = 0,sex = 2,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,35}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10012] = {id = 10012,name = "一阶衣服（女）",level = 1,rank = 1,type = 1,pos = 2,quality = 0,sex = 2,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,23}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10013] = {id = 10013,name = "一阶护手（女）",level = 1,rank = 1,type = 1,pos = 3,quality = 0,sex = 2,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10014] = {id = 10014,name = "一阶腰带（女）",level = 1,rank = 1,type = 1,pos = 4,quality = 0,sex = 2,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,167}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10015] = {id = 10015,name = "一阶鞋子（女）",level = 1,rank = 1,type = 1,pos = 5,quality = 0,sex = 2,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,14}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10016] = {id = 10016,name = "一阶头饰（女）",level = 1,rank = 1,type = 1,pos = 6,quality = 0,sex = 2,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,167}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10017] = {id = 10017,name = "一阶项链（女）",level = 1,rank = 1,type = 1,pos = 7,quality = 0,sex = 2,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10018] = {id = 10018,name = "一阶手镯（女）",level = 1,rank = 1,type = 1,pos = 8,quality = 0,sex = 2,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10019] = {id = 10019,name = "一阶戒指（女）",level = 1,rank = 1,type = 1,pos = 9,quality = 0,sex = 2,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,5}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10020] = {id = 10020,name = "一阶腰坠（女）",level = 1,rank = 1,type = 1,pos = 10,quality = 0,sex = 2,price = 10,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,3}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10021] = {id = 10021,name = "二阶武器（男）",level = 1,rank = 2,type = 1,pos = 1,quality = 1,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,70}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10022] = {id = 10022,name = "二阶衣服（男）",level = 1,rank = 2,type = 1,pos = 2,quality = 1,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,46}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10023] = {id = 10023,name = "二阶护手（男）",level = 1,rank = 2,type = 1,pos = 3,quality = 1,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,40}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10024] = {id = 10024,name = "二阶腰带（男）",level = 1,rank = 2,type = 1,pos = 4,quality = 1,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10025] = {id = 10025,name = "二阶鞋子（男）",level = 1,rank = 2,type = 1,pos = 5,quality = 1,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,28}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10026] = {id = 10026,name = "二阶头饰（男）",level = 1,rank = 2,type = 1,pos = 6,quality = 1,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10027] = {id = 10027,name = "二阶项链（男）",level = 1,rank = 2,type = 1,pos = 7,quality = 1,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10028] = {id = 10028,name = "二阶手镯（男）",level = 1,rank = 2,type = 1,pos = 8,quality = 1,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10029] = {id = 10029,name = "二阶戒指（男）",level = 1,rank = 2,type = 1,pos = 9,quality = 1,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10030] = {id = 10030,name = "二阶腰坠（男）",level = 1,rank = 2,type = 1,pos = 10,quality = 1,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,6}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10031] = {id = 10031,name = "二阶武器（女）",level = 1,rank = 2,type = 1,pos = 1,quality = 1,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,70}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10032] = {id = 10032,name = "二阶衣服（女）",level = 1,rank = 2,type = 1,pos = 2,quality = 1,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,46}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10033] = {id = 10033,name = "二阶护手（女）",level = 1,rank = 2,type = 1,pos = 3,quality = 1,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,40}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10034] = {id = 10034,name = "二阶腰带（女）",level = 1,rank = 2,type = 1,pos = 4,quality = 1,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10035] = {id = 10035,name = "二阶鞋子（女）",level = 1,rank = 2,type = 1,pos = 5,quality = 1,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,28}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10036] = {id = 10036,name = "二阶头饰（女）",level = 1,rank = 2,type = 1,pos = 6,quality = 1,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10037] = {id = 10037,name = "二阶项链（女）",level = 1,rank = 2,type = 1,pos = 7,quality = 1,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10038] = {id = 10038,name = "二阶手镯（女）",level = 1,rank = 2,type = 1,pos = 8,quality = 1,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10039] = {id = 10039,name = "二阶戒指（女）",level = 1,rank = 2,type = 1,pos = 9,quality = 1,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10040] = {id = 10040,name = "二阶腰坠（女）",level = 1,rank = 2,type = 1,pos = 10,quality = 1,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,6}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10041] = {id = 10041,name = "三阶武器（男）",level = 1,rank = 3,type = 1,pos = 1,quality = 2,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,70}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10042] = {id = 10042,name = "三阶衣服（男）",level = 1,rank = 3,type = 1,pos = 2,quality = 2,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,46}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10043] = {id = 10043,name = "三阶护手（男）",level = 1,rank = 3,type = 1,pos = 3,quality = 2,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,40}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10044] = {id = 10044,name = "三阶腰带（男）",level = 1,rank = 3,type = 1,pos = 4,quality = 2,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10045] = {id = 10045,name = "三阶鞋子（男）",level = 1,rank = 3,type = 1,pos = 5,quality = 2,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,28}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10046] = {id = 10046,name = "三阶头饰（男）",level = 1,rank = 3,type = 1,pos = 6,quality = 2,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10047] = {id = 10047,name = "三阶项链（男）",level = 1,rank = 3,type = 1,pos = 7,quality = 2,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10048] = {id = 10048,name = "三阶手镯（男）",level = 1,rank = 3,type = 1,pos = 8,quality = 2,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10049] = {id = 10049,name = "三阶戒指（男）",level = 1,rank = 3,type = 1,pos = 9,quality = 2,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10050] = {id = 10050,name = "三阶腰坠（男）",level = 1,rank = 3,type = 1,pos = 10,quality = 2,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,6}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10051] = {id = 10051,name = "三阶武器（女）",level = 1,rank = 3,type = 1,pos = 1,quality = 2,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,70}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10052] = {id = 10052,name = "三阶衣服（女）",level = 1,rank = 3,type = 1,pos = 2,quality = 2,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,46}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10053] = {id = 10053,name = "三阶护手（女）",level = 1,rank = 3,type = 1,pos = 3,quality = 2,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,40}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10054] = {id = 10054,name = "三阶腰带（女）",level = 1,rank = 3,type = 1,pos = 4,quality = 2,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10055] = {id = 10055,name = "三阶鞋子（女）",level = 1,rank = 3,type = 1,pos = 5,quality = 2,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,28}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10056] = {id = 10056,name = "三阶头饰（女）",level = 1,rank = 3,type = 1,pos = 6,quality = 2,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10057] = {id = 10057,name = "三阶项链（女）",level = 1,rank = 3,type = 1,pos = 7,quality = 2,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10058] = {id = 10058,name = "三阶手镯（女）",level = 1,rank = 3,type = 1,pos = 8,quality = 2,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10059] = {id = 10059,name = "三阶戒指（女）",level = 1,rank = 3,type = 1,pos = 9,quality = 2,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10060] = {id = 10060,name = "三阶腰坠（女）",level = 1,rank = 3,type = 1,pos = 10,quality = 2,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,6}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10061] = {id = 10061,name = "四阶武器（男）",level = 1,rank = 4,type = 1,pos = 1,quality = 3,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,70}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10062] = {id = 10062,name = "四阶衣服（男）",level = 1,rank = 4,type = 1,pos = 2,quality = 3,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,46}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10063] = {id = 10063,name = "四阶护手（男）",level = 1,rank = 4,type = 1,pos = 3,quality = 3,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,40}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10064] = {id = 10064,name = "四阶腰带（男）",level = 1,rank = 4,type = 1,pos = 4,quality = 3,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10065] = {id = 10065,name = "四阶鞋子（男）",level = 1,rank = 4,type = 1,pos = 5,quality = 3,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,28}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10066] = {id = 10066,name = "四阶头饰（男）",level = 1,rank = 4,type = 1,pos = 6,quality = 3,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10067] = {id = 10067,name = "四阶项链（男）",level = 1,rank = 4,type = 1,pos = 7,quality = 3,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10068] = {id = 10068,name = "四阶手镯（男）",level = 1,rank = 4,type = 1,pos = 8,quality = 3,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10069] = {id = 10069,name = "四阶戒指（男）",level = 1,rank = 4,type = 1,pos = 9,quality = 3,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10070] = {id = 10070,name = "四阶腰坠（男）",level = 1,rank = 4,type = 1,pos = 10,quality = 3,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,6}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10071] = {id = 10071,name = "四阶武器（女）",level = 1,rank = 4,type = 1,pos = 1,quality = 3,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,70}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10072] = {id = 10072,name = "四阶衣服（女）",level = 1,rank = 4,type = 1,pos = 2,quality = 3,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,46}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10073] = {id = 10073,name = "四阶护手（女）",level = 1,rank = 4,type = 1,pos = 3,quality = 3,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,40}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10074] = {id = 10074,name = "四阶腰带（女）",level = 1,rank = 4,type = 1,pos = 4,quality = 3,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10075] = {id = 10075,name = "四阶鞋子（女）",level = 1,rank = 4,type = 1,pos = 5,quality = 3,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,28}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10076] = {id = 10076,name = "四阶头饰（女）",level = 1,rank = 4,type = 1,pos = 6,quality = 3,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10077] = {id = 10077,name = "四阶项链（女）",level = 1,rank = 4,type = 1,pos = 7,quality = 3,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10078] = {id = 10078,name = "四阶手镯（女）",level = 1,rank = 4,type = 1,pos = 8,quality = 3,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10079] = {id = 10079,name = "四阶戒指（女）",level = 1,rank = 4,type = 1,pos = 9,quality = 3,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10080] = {id = 10080,name = "四阶腰坠（女）",level = 1,rank = 4,type = 1,pos = 10,quality = 3,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,6}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10081] = {id = 10081,name = "五阶武器（男）",level = 1,rank = 5,type = 1,pos = 1,quality = 4,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,70}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10082] = {id = 10082,name = "五阶衣服（男）",level = 1,rank = 5,type = 1,pos = 2,quality = 4,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,46}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10083] = {id = 10083,name = "五阶护手（男）",level = 1,rank = 5,type = 1,pos = 3,quality = 4,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,40}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10084] = {id = 10084,name = "五阶腰带（男）",level = 1,rank = 5,type = 1,pos = 4,quality = 4,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10085] = {id = 10085,name = "五阶鞋子（男）",level = 1,rank = 5,type = 1,pos = 5,quality = 4,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,28}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10086] = {id = 10086,name = "五阶头饰（男）",level = 1,rank = 5,type = 1,pos = 6,quality = 4,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10087] = {id = 10087,name = "五阶项链（男）",level = 1,rank = 5,type = 1,pos = 7,quality = 4,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10088] = {id = 10088,name = "五阶手镯（男）",level = 1,rank = 5,type = 1,pos = 8,quality = 4,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10089] = {id = 10089,name = "五阶戒指（男）",level = 1,rank = 5,type = 1,pos = 9,quality = 4,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10090] = {id = 10090,name = "五阶腰坠（男）",level = 1,rank = 5,type = 1,pos = 10,quality = 4,sex = 1,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,6}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10091] = {id = 10091,name = "五阶武器（女）",level = 1,rank = 5,type = 1,pos = 1,quality = 4,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,70}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10092] = {id = 10092,name = "五阶衣服（女）",level = 1,rank = 5,type = 1,pos = 2,quality = 4,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,46}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10093] = {id = 10093,name = "五阶护手（女）",level = 1,rank = 5,type = 1,pos = 3,quality = 4,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,40}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10094] = {id = 10094,name = "五阶腰带（女）",level = 1,rank = 5,type = 1,pos = 4,quality = 4,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10095] = {id = 10095,name = "五阶鞋子（女）",level = 1,rank = 5,type = 1,pos = 5,quality = 4,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,28}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10096] = {id = 10096,name = "五阶头饰（女）",level = 1,rank = 5,type = 1,pos = 6,quality = 4,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10097] = {id = 10097,name = "五阶项链（女）",level = 1,rank = 5,type = 1,pos = 7,quality = 4,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10098] = {id = 10098,name = "五阶手镯（女）",level = 1,rank = 5,type = 1,pos = 8,quality = 4,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10099] = {id = 10099,name = "五阶戒指（女）",level = 1,rank = 5,type = 1,pos = 9,quality = 4,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10100] = {id = 10100,name = "五阶腰坠（女）",level = 1,rank = 5,type = 1,pos = 10,quality = 4,sex = 2,price = 30,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,6}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10101] = {id = 10101,name = "六阶武器（男）",level = 1,rank = 6,type = 1,pos = 1,quality = 5,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,70}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10102] = {id = 10102,name = "六阶衣服（男）",level = 1,rank = 6,type = 1,pos = 2,quality = 5,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,46}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10103] = {id = 10103,name = "六阶护手（男）",level = 1,rank = 6,type = 1,pos = 3,quality = 5,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,40}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10104] = {id = 10104,name = "六阶腰带（男）",level = 1,rank = 6,type = 1,pos = 4,quality = 5,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10105] = {id = 10105,name = "六阶鞋子（男）",level = 1,rank = 6,type = 1,pos = 5,quality = 5,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,28}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10106] = {id = 10106,name = "六阶头饰（男）",level = 1,rank = 6,type = 1,pos = 6,quality = 5,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10107] = {id = 10107,name = "六阶项链（男）",level = 1,rank = 6,type = 1,pos = 7,quality = 5,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10108] = {id = 10108,name = "六阶手镯（男）",level = 1,rank = 6,type = 1,pos = 8,quality = 5,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10109] = {id = 10109,name = "六阶戒指（男）",level = 1,rank = 6,type = 1,pos = 9,quality = 5,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10110] = {id = 10110,name = "六阶腰坠（男）",level = 1,rank = 6,type = 1,pos = 10,quality = 5,sex = 1,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,6}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10111] = {id = 10111,name = "六阶武器（女）",level = 1,rank = 6,type = 1,pos = 1,quality = 5,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,70}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10112] = {id = 10112,name = "六阶衣服（女）",level = 1,rank = 6,type = 1,pos = 2,quality = 5,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,46}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10113] = {id = 10113,name = "六阶护手（女）",level = 1,rank = 6,type = 1,pos = 3,quality = 5,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{2,40}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10114] = {id = 10114,name = "六阶腰带（女）",level = 1,rank = 6,type = 1,pos = 4,quality = 5,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10115] = {id = 10115,name = "六阶鞋子（女）",level = 1,rank = 6,type = 1,pos = 5,quality = 5,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{3,28}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10116] = {id = 10116,name = "六阶头饰（女）",level = 1,rank = 6,type = 1,pos = 6,quality = 5,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{1,334}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10117] = {id = 10117,name = "六阶项链（女）",level = 1,rank = 6,type = 1,pos = 7,quality = 5,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{4,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10118] = {id = 10118,name = "六阶手镯（女）",level = 1,rank = 6,type = 1,pos = 8,quality = 5,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{5,20}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10119] = {id = 10119,name = "六阶戒指（女）",level = 1,rank = 6,type = 1,pos = 9,quality = 5,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{6,10}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[10120] = {id = 10120,name = "六阶腰坠（女）",level = 1,rank = 6,type = 1,pos = 10,quality = 5,sex = 2,price = 20,is_transaction = 0,max_overlap = 1,is_slather = 0,use_result = 0,basic_properties = {{7,6}},suit_id = {},using_effect = {},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 0,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[50001] = {id = 50001,name = "1级生命药水",level = 1,rank = 0,type = 12,pos = 0,quality = 1,sex = 0,price = 10,is_transaction = 0,max_overlap = 99,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {{1,200}},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 600,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
	[50002] = {id = 50002,name = "2级生命药水",level = 1,rank = 0,type = 12,pos = 0,quality = 2,sex = 0,price = 20,is_transaction = 0,max_overlap = 99,is_slather = 0,use_result = 0,basic_properties = {},suit_id = {},using_effect = {{1,500}},use_limit = 0,category = 0,category_cooldown = 0,cooldown = 600,is_discard = 0,goods_id = 0,expend_data = 0,use_object = 0,quest = 0,forge_pro = {},forge_pro_max = {},is_auction = 0,auction_money = 0,},
}
