--------------------------------------------------------------------------------------------------------------------------
--------------------------------------------以下代码为自动生成，请勿手工改动----------------------------------------------
--------------------------------------------------------------------------------------------------------------------------

MAX_MONEY = 2e+015	-- 最大金额数，超过下线再上就白瞎
MAX_MONEY_TRUE = 4e+015	-- 最大金额数.真。超过就不再往上加
MAX_BUFF_DURATION = 65535	-- 无限BUFF时间
ZHUCHENG_DITU_ID = 1	-- 主城地图ID
ZHUCHENG_FUHUO_X = 56	-- 主城复活点
ZHUCHENG_FUHUO_Y = 92	-- 主城复活点
MAX_RMB_PLAYER_LEVEL = 6	-- 最大的RMB等级
-- 服务器类型枚举
WORLD_SERVER_TYPE_GAME = 0	-- 游戏服
WORLD_SERVER_TYPE_PK = 1	-- pk服
-- 跨服类型枚举
KUAFU_TYPE_NONE = 0
KUAFU_TYPE_FENGLIUZHEN = 1	-- 跨服风流镇
MAX_KUAFU_TYPE = 2
-- 合服协议带的类型
MERGE_TYPE_MERGE = 0	-- 从服迁移连接到主服
MERGE_TYPE_GAME_TO_PK = 1	-- 游戏服到Pk服
MERGE_TYPE_PK_TO_GAME = 2	-- pk服到游戏服
-- 会话类型
CONTEXT_TYPE_YEYOU = 0	-- 页游
CONTEXT_TYPE_PHONE = 1	-- 手游
MAX_CONTEXT_TYPE = 2
-- 性别
CHAR_GENDER_MALE = 0	-- 男性
CHAR_GENDER_FEMALE = 1	-- 女性
CHAR_GENDER_NONE = 2	-- 未知
MAX_CHAR_GENDER = 3	-- 长度		
-- 形象
RACE_NONE = 0	-- 无
RACE_STRONG = 1	-- 壮男
RACE_HANDSOME = 2	-- 俊男 
RACE_LAURIE = 3	-- 萝莉
RACE_BEAUTY = 4	-- 美人
-- 头像
HEAD_NONE = 0	-- 无
HEAD_STRONG = 1	-- 壮男
HEAD_HANDSOME = 2	-- 俊男 
HEAD_LAURIE = 3	-- 萝莉
HEAD_BEAUTY = 4	-- 美人	
HEAD_TOTAL = 4
-- 复活类型
RESURRECTION_IN_SITU = 0	-- 原地复活
RESURRECTION_SPAWNPOINT = 1	-- 复活点复活
RESURRPCTION_FREE = 2	-- 免费复活
RESURRPCTION_MONEY = 3	-- 元宝复活
RESURRPCTION_TIME = 4	-- 超时复活
RESURRPCTION_HUANHUNDAN = 5	-- 还魂丹复活
MAX_RESURRECTION_TYPE = 6
-- GM等级
GM_LEVEL_0 = 0	-- 普通玩家
GM_LEVEL_1 = 1	-- 普通GM
GM_LEVEL_2 = 2	-- 高级GM
GM_LEVEL_3 = 3	-- 终极GM
-- 游戏对象标志
GO_FLAG_DYNAMIC = 0	-- 是否动态对象,由不是由地图刷出来的
GO_FLAG_TELE = 1	-- 是否传送点对象
GO_FLAG_QUEST = 2	-- 是否任务对象
GO_FLAG_LOOT = 3	-- 是否战利品	
GO_FLAG_GEAR = 10	-- 是否机关，如箱子，门等
GO_FLAG_UNUSE = 4	-- 不可被使用
GO_FLAG_FOREVER = 5	-- 可永久使用
GO_FLAG_USEMODE = 8	-- 使用方式,需要进度条
GO_FLAG_CARTON = 9	-- 客户端模拟消失
GO_FLAG_SCRIPT = 12	-- 是否使用脚本
GO_FLAG_GET_ITEM_NOTICE = 13	-- 拾起物品是否需要公告
-- 世界地图状态
WORLD_MAP_DEFAULT = 0	-- 新手村
-- 类枚举
TYPEID_OBJECT = 0	-- 本来0都是没用的
TYPEID_UNIT = 1	-- 生物精灵，如怪物，NPC，宝宝等。。。
TYPEID_PLAYER = 2	-- 玩家精灵
TYPEID_GAMEOBJECT = 3	-- 游戏对象精灵
MAX_CLIENT_OBJECT_TYPES = 4
-- 物品品质
ITEM_QUAL_WHITE = 0	-- 白装
ITEM_QUAL_GREEN = 1	-- 绿装
ITEM_QUAL_BLUE = 2	-- 蓝装
ITEM_QUAL_PURPLE = 3	-- 紫装
ITEM_QUAL_ORANGE = 4	-- 橙装
ITEM_QUAL_RED = 5	-- 红装
MAX_QUAL = 6
-- 攻击模式
ATTACK_MODE_PEACE = 0	-- 和平，不用说，你懂的
ATTACK_MODE_TEAM = 1	-- 组队，可以砍队伍以外的玩家
ATTACK_MODE_RED = 2	-- 红名，可以砍红名
ATTACK_MODE_ALL = 3	-- 全体，除了自己，谁都可以砍
ATTACK_MODE_FACTION = 4	-- 帮派模式
ATTACK_MODE_BANG = 5	-- 结义模式
MAX_ATTACK_MODE = 6
-- 仇恨计算类型
REACT_PASSIVE = 0	-- 被动攻击
REACT_DEFENSIVE = 1	-- 防御
REACT_AGGRESSIVE = 2	-- 主动攻击,
REACT_AGGRESSIVE_UNIT = 3	-- 主动攻击怪物
REACT_AGGRESSIVE_PLAYER = 4	-- 主动攻击玩家
MAX_REACT_STATES = 5
-- 合服操作类型
MERGE_OPT_TYPE_INIT = 0	-- 初始状态
MERGE_OPT_TYPE_SAVE_DB = 1	-- 数据保存完成
MERGE_OPT_TYPE_TARGET_SERVER_OK = 2	-- 目标服务器准备完成
MERGE_OPT_TYPE_END = 3	-- 操作结束
MERGE_OPT_TYPE_SAVE_ING = 4	-- 数据保存中
-- 合服服务器类型
MERGE_SERVER_TYPE_ORIGINAL = 1	-- 原始服务器
MERGE_SERVER_TYPE_TARGAT = 2	-- 目标服务器
-- 回档操作类型
BACK_OPT_TYPE_INIT = 0	-- 初始状态
BACK_OPT_TYPE_SUCCESS = 1	-- 成功
-- 物品绑定类型
ITEM_BIND_NONE = 0	-- 非绑定
ITEM_BIND_USE = 1	-- 使用绑定
ITEM_BIND_GET = 2	-- 获得绑定
-- 场景服给的东西获得类型
ITEM_GIFT_GET_NONE = 0	-- 非必须
ITEM_GIFT_GET_MUST = 1	-- 必须获得的
-- 玩家在线状态
PLAYER_ONLINE_STATE_OUTLINE = 0	-- 离线
PLAYER_ONLINE_STATE_ONLINE = 1	-- 在线
-- 生物移动模式
DISAPPEAR_MOTION_TYPE = 9999	-- 消失
IDLE_MOTION_TYPE = 0	-- 空闲
RANDOM_MOTION_TYPE = 1	-- 随机
WAYPOINT_MOTION_TYPE = 2	-- 沿路行走
TARGET_MOTION_TYPE = 3	-- 目标行走
HOME_MOTION_TYPE = 4	-- 回家
CONFUSED_MOTION_TYPE = 5	-- 困惑
FLEEING_MOTION_TYPE = 6	-- 逃避
FOLLOW_MOTION_TYPE = 7	-- 跟随
FOLLOW_INLINE_MOTION_TYPE = 8	-- 直线跟随
WAYFINDING_MOTION_TYPE = 9	-- 寻路行走
WAYFINDING_ATTACK_MOTION_TYPE = 10	-- 寻路追杀
MERCENARY_MOTION_TYPE = 11	-- 佣兵
WAYFINDDST_MOTION_TYPE = 12	-- 目的地行走
MAX_MOTION_TYPE = 13
-- 技能目标类型 自己,友方,敌方,全体
TARGET_TYPE_ONESELF = 0
TARGET_TYPE_FRIENDLY = 1
TARGET_TYPE_ENEMY = 2
TARGET_TYPE_ALL = 3
TARGET_TYPE_POINT = 4	-- 对点释放技能 
TARGET_TYPE_SELFPOINT = 5	-- 对自己的点释放
TARGET_TYPE_CREATURE = 6	-- 对怪物有效（不包括宠物等）
TARGET_TYPE_PLAYER = 7	-- 对玩家有效
-- 交易状态
TRADE_STATE_TYPE_FREE = 0	-- 空闲状态
TRADE_STATE_TYPE_APPLY = 1	-- 申请状态
TRADE_STATE_TYPE_EXECUTION = 2	-- 执行状态
TRADE_STATE_TYPE_PUT_ITEM_END = 3	-- 确认物品完成
TRADE_STATE_TYPE_WAIT_FINISH = 4	-- 等待完成状态
-- 交易的类型
TRADE_TYPE_TRADE = 0	-- 交易
TRADE_TYPE_STALL = 1	-- 摆摊
-- 通过模板id移动物品到指定的包裹（相应的位置上），结果
MOVE_ITEM_FAIL = 0	-- 失败
MOVE_ITEM_SUC = 1	-- 成功
MOVE_ITEM_HAVE_BIND = 2	-- 包含绑定的
MOVE_ITEM_NOT_BIND = 3	-- 不包含绑定的
-- 删除物品结果
SUB_ITEM_FAIL = 0	-- 失败
SUB_ITEM_HAVE_BIND = 1	-- 包含绑定的
SUB_ITEM_NOT_BIND = 2	-- 不包含绑定的
SUB_ITEM_HAVE_FAILTIME = 3	-- 包含限时
-- 物品数据处理状态
ITEM_SAVE_MODE_INSERT = 0	-- 插入
ITEM_SAVE_MODE_UPDATE = 1	-- 更新
-- 元宝充值类型
GOLD_INGOT_RECHARGE_NORMAL = 1	-- 正常模式
GOLD_INGOT_RECHARGE_HANDSEL = 2	-- 赠送模式
GOLD_INGOT_RECHARGE_SUB = 3	-- 扣费模式
GOLD_INGOT_RECHARGE_HAND = 4	-- 手动模式
MAX_GOLD_INGOT_RECHARGE_TYPE = 5
-- 充值状态类型
RECHARGE_STATUS_TYPE_START = 0	-- 初始化
RECHARGE_STATUS_TYPE_RUNMING = 1	-- 发放中
RECHARGE_STATUS_TYPE_END = 2	-- 结束
-- 踢人的状态类型
KICKING_STATUS_START = 0	-- 初始化
KICKING_STATUS_END = 1	-- 已踢
-- 封号的状态类型
LOCKING_STATUS_START = 0	-- 初始化
LOCKING_STATUS_RUNNING = 1	-- 封号中
LOCKING_STATUS_END = 2	-- 结束
-- 公告的状态类型
SYSTEM_NOTICE_STATUS_START = 0	-- 初始状态
SYSTEM_NOTICE_STATUS_RUNNING = 1	-- 运行中
SYSTEM_NOTICE_STATUS_END = 2	-- 结束
SYSTEM_NOTICE_STATUS_DELETE = 3	-- 将删除
SYSTEM_NOTICE_STATUS_GARBAGE = 4	-- 已删除
-- 礼包的状态类型
GIFT_PACKS_STATUS_START = 0	-- 初始
GIFT_PACKS_STATUS_SENDING = 1	-- 发放中
GIFT_PACKS_STATUS_OK = 2	-- 已发放
GIFT_PACKS_STATUS_END = 3	-- 已结束
-- 礼包发放类型
GIFT_PACKS_AUDIENCE_TYPE_ONE = 1	-- 个人礼包，如补偿礼包等
GIFT_PACKS_AUDIENCE_TYPE_ALL = 2	-- 全体同志的礼包
GIFT_PACKS_AUDIENCE_TYPE_ALL_ONLINE = 3	-- 全服在线玩家
-- 礼包操作类型
GIFT_PACKS_OPER_TYPE_RECEIVE = 0	-- 领取
GIFT_PACKS_OPER_TYPE_READ = 1	-- 已读
GIFT_PACKS_OPER_TYPE_DELETE = 2	-- 删除
-- 禁言状态
GAG_STATUS_START = 0	-- 初始化
GAG_STATUS_OFFLINE = 1	-- GAG_STATUS_OFFLINE		= 1,		//玩家离线
GAG_STATUS_END = 1	-- 已禁言
-- 设置GM表的状态
GM_LEVEL_TABLE_START = 0	-- 初始化
GM_LEVEL_TABLE_END = 1	-- 已执行
-- 公告类型
NOTICE_TYPE_SCROLL = 1	-- 滚动公告
NOTICE_TYPE_PROMPT = 2	-- 固定和世界聊天提示
NOTICE_TYPE_FIXED = 3	-- 固定提示
MAX_NOTICE_TYPE = 10	-- 预留10种
-- 聊天类型
CHAT_TYPE_WORLD = 0
CHAT_TYPE_FACTION = 1
CHAT_TYPE_WHISPER = 2
CHAT_TYPE_CURRENT = 3
CHAT_TYPE_HORM = 4
CHAT_TYPE_NOTICE = 5
CHAT_TYPE_GROUP = 6
CHAT_TYPE_TRADE = 7
MAX_CHAT_TYPE = 8
-- 平台枚举
PLATFORM_GAME2 = "2"	-- 哥们网
PLATFORM_QQ = "360"	-- 腾讯QQ
PLATFORM_NULL = "9999"	-- 不需要post的平台
-- post的动作类型
POST_TYPE_NONE = 0
POST_TYPE_CHAT = 1	-- 聊天
POST_TYPE_UPGRADE = 2	-- 用户升级
MAX_POST_TYPE = 3
-- 记录到文件的日志类型
LOG_FILE_TYPE_GAME_BUY = 0	-- 记录用户在游戏内购买行为
LOG_FILE_TYPE_GAME_SELL = 1	-- 记录用户在游戏内出售行为
LOG_FILE_TYPE_RECHARGE = 2	-- 记录用户充值行为
LOG_FILE_TYPE_SHOP_BUY = 3	-- 记录用户在商城的购买行为
LOG_FILE_TYPE_ITEM_USE = 4	-- 记录用户使用商城物品行为
LOG_FILE_TYPE_DEAL = 5	-- 记录用户的交易行为
LOG_FILE_TYPE_YB_INCOME = 6	-- 记录额外元宝收入
LOG_FILE_TYPE_ITEM_INCOME = 7	-- 记录额外道具收入
LOG_FILE_TYPE_YB_EXPEND = 8	-- 记录额外元宝消费
LOG_FILE_TYPE_LOGIN = 9	-- 记录用户登录行为
LOG_FILE_TYPE_LOGOUT = 10	-- 记录用户登出行为
LOG_FILE_TYPE_CREATE_ROLE = 11	-- 记录用户创建角色行为
LOG_FILE_TYPE_DEATH = 12	-- 记录用户角色死亡事件
LOG_FILE_TYPE_ACCEPT_TASK = 13	-- 记录用户接收任务的行为
LOG_FILE_TYPE_TASK = 14	-- 记录用户完成任务的行为
LOG_FILE_TYPE_UPGRADE = 15	-- 记录用户升级事件
LOG_FILE_TYPE_GOLD = 16	-- 记录用户金币所得行为
LOG_FILE_TYPE_MAP = 17	-- 记录用户切换地图的行为
LOG_FILE_TYPE_LONGER = 18	-- 记录用户的挂机行为
LOG_FILE_TYPE_MONSTER = 19	-- 记录用户打怪的行为
LOG_FILE_TYPE_TRANSCRIPT = 20	-- 记录用户打副本的行为
LOG_FILE_TYPE_ONLINE = 21	-- 记录在线人数
LOG_FILE_TYPE_GAME_ENTER = 22	-- 记录用户进入游戏主界面
LOG_FILE_TYPE_ITEM_LOG = 23	-- 记录道具的所有行为
LOG_FILE_TYPE_CHAT = 24	-- 记录玩家聊天记录
LOG_FILE_TYPE_RELIVE = 25	-- 记录玩家复活
LOG_FILE_TYPE_BIND_GOLD = 26	-- 记录玩家的绑定元宝行为
LOG_FILE_TYPE_NEW_CARD_RECEIVE = 27	-- 记录用户领取新手卡的行为
LOG_FILE_TYPE_STALL = 28	-- 记录摆摊行为
LOG_FILE_TYPE_WANTED_PACKET = 29	-- 记录被通缉的玩家的所有包记录
LOG_FILE_TYPE_ERROR_PACKET = 30	-- 记录读取用户信息出错的包
LOG_FILE_TYPE_CHOOSE_FACTION = 31	-- 记录玩家选择阵营的情况
LOG_FILE_TYPE_ACTIVITY_INFO = 32	-- 记录运营活动奖励信息
LOG_FILE_TYPE_ABNORMAL_PACKETS = 33	-- 记录因为异常包而踢掉玩家的行为
LOG_FILE_TYPE_CLIENT_INFO = 34	-- 记录玩家客户端信息
LOG_FILE_TYPE_GIFTMONEY_BUY = 35	-- 记录玩家礼金消耗的行为
LOG_FILE_TYPE_GIFTMONEY_INCOME = 36	-- 记录用户礼金获得的行为
LOG_FILE_TYPE_ATTACK_PACKET = 37	-- 记录攻击包
LOG_FILE_TYPE_FORMAT_LOG = 38	-- 记录乱七八糟的自定义日志
LOG_FILE_TYPE_CLIENT_LOG = 39	-- 记录客户端日志
LOG_FILE_TYPE_FORGE_LOG = 40	-- 记录锻造日志
LOG_FILE_TYPE_OBJECT_LOSS = 41	-- 1001日志
MAX_LOG_FILE_TYPE = 42
-- 记录腾讯文件的日志类型
LOG_FILE_TENCENT_USER = 0	-- 用户表
LOG_FILE_TENCENT_PLAYER = 1	-- 角色表
LOG_FILE_TENCENT_RECHAGRE = 2	-- 充值表
LOG_FILE_TENCENT_UPGRADELOG = 3	-- 升级日志
LOG_FILE_TENCENT_NEWTASK = 4	-- 新手日志
LOG_FILE_TENCENT_LOGIN = 5	-- 登陆日志
LOG_FILE_TENCENT_OFFLINE = 6	-- 离线日志
LOG_FILE_TENCENT_ONLINE = 7	-- 在线统计日志
LOG_FILE_TENCENT_MONEYLOG = 8	-- 金币流量
MAX_LOG_FILE_TENCENT_TYPE = 9
-- 攻击包异常类型
ACCACK_PACKET_TYPE_UNPACK = 0	-- 解包失败
ACCACK_PACKET_TYPE_DATA = 1	-- 数据异常
ACCACK_PACKET_TYPE_ORDER = 2	-- 包顺序异常
ACCACK_PACKET_TYPE_DISCARD = 3	-- 废弃的包号
MAX_ACCACK_PACKET_TYPE = 4
-- 交易物品
-- 装备ID
-- 模版ID
-- 类型
-- 数量
-- 额外元宝获得类型
LOG_YB_INCOME_TYPE_ACTIVITY = 0	-- 活动赠送
LOG_YB_INCOME_TYPE_RECHARGE = 1	-- 充值赠送
LOG_YB_INCOME_TYPE_USE_ITEM = 2	-- 使用道具
LOG_YB_INCOME_TYPE_GIFT_PACKS = 3	-- 补偿礼包
-- 道具操作类型
-- 获得
LOG_ITEM_OPER_TYPE_ACTIVITY = 0	-- 活动奖励获得
LOG_ITEM_OPER_TYPE_RECHARGE = 1	-- 充值赠送获得
LOG_ITEM_OPER_TYPE_GIFT_PACKS = 2	-- 补偿礼包获得
LOG_ITEM_OPER_TYPE_QUEST = 3	-- 任务完成奖励获得
LOG_ITEM_OPER_TYPE_NEWPLAYER = 4	-- 新手礼包获得
LOG_ITEM_OPER_TYPE_OPEN_ITEM = 5	-- 使用道具获得
LOG_ITEM_OPER_TYPE_LOOT = 6	-- 战利品
LOG_ITEM_OPER_TYPE_GM_COMMAND = 7	-- GM命令获得
LOG_ITEM_OPER_TYPE_ITEM_BLEND = 8	-- 物品合成获得
LOG_ITEM_OPER_TYPE_SEVEN_DAY_GIFT = 9	-- 连登礼包	
LOG_ITEM_OPER_TYPE_JHM_GIFT = 10	-- 激活码礼包
LOG_ITEM_OPER_TYPE_OPEN_BOX = 11	-- 开宝箱获得
LOG_ITEM_OPER_TYPE_FUBEN_EWAIJINAGLI = 12	-- 副本额外奖励
LOG_ITEM_OPER_TYPE_CAPTURE_YAOHUN = 13	-- 扑捉妖魂获得
LOG_ITEM_OPER_TYPE_FSZL_EWAIJINAGLI = 14	-- 飞升之路奖励
LOG_ITEM_OPER_TYPE_PRESTIGE = 15	-- 活跃度领取获得
LOG_ITEM_OPER_TYPE_TIANDILINGKUANG = 16	-- 天地灵矿领取获得
LOG_ITEM_OPER_TYPE_PANTAOYUAN = 17	-- 蟠桃园奖励
LOG_ITEM_OPER_TYPE_WABAO = 18	-- 挖宝获得
LOG_ITEM_OPER_TYPE_HONGYAN = 19	-- 红颜事件获得
LOG_ITEM_OPER_TYPE_FORGE_DECOMPOSE = 20	-- 锻造分解获得
-- 购买
LOG_ITEM_OPER_TYPE_SHOP_BUY = 101	-- 从商场购买获得
LOG_ITEM_OPER_TYPE_NPC_BUY = 102	-- 从NPC购买获得
LOG_ITEM_OPER_TYPE_BIND_SHOP_BUY = 103	-- 从绑定商城购买获得
LOG_ITEM_OPER_TYPE_REPURCHASE = 104	-- 从NPC回购物品获得
LOG_ITEM_OPER_TYPE_ACTI_BUY = 105	-- 活动购买	
-- 消耗
LOG_ITEM_OPER_TYPE_NPC_SELL = 200	-- 出售给NPC
LOG_ITEM_OPER_TYPE_DEL_FAILTIME = 201	-- 清理限时物品
LOG_ITEM_OPER_TYPE_USE = 202	-- 使用物品
LOG_ITEM_OPER_TYPE_DISPOSE = 203	-- 销毁物品
LOG_ITEM_OPER_TYPE_HEAL = 204	-- 吃药
-- 交易
LOG_ITEM_OPER_TYPE_TRADE_GET = 301	-- 交易获得
LOG_ITEM_OPER_TYPE_TRADE_PAY = 302	-- 交易付出
LOG_ITEM_OPER_TYPE_STALL_OPEN = 303	-- 摆摊
LOG_ITEM_OPER_TYPE_STALL_CLOSE = 304	-- 收摊
LOG_ITEM_OPER_TYPE_STALL_BUY = 305	-- 摊位购买
LOG_ITEM_OPER_TYPE_LINGDI_XUANSHANG = 306	-- 领地悬赏
LOG_ITEM_OPER_TYPE_LINGDI_MIJING = 307	-- 领地秘境
LOG_ITEM_OPER_TYPE_WUJIANG_ZHENGZHAN = 308	-- 武将征战
LOG_ITEM_OPER_TYPE_KAOZHUANGYUAN = 309	-- 考状元
-- 后台货币变化种类枚举
HT_MONEY_CHANGE_TYPE_RECHARGE = 1	-- 充值
HT_MONEY_CHANGE_TYPE_CONSUMPTION = 2	-- 消费
HT_MONEY_CHANGE_TYPE_SUB = 3	-- 管理员扣除
HT_MONEY_CHANGE_TYPE_REWARD = 4	-- 奖励
HT_MONEY_CHANGE_TYPE_REBATE = 5	-- 返利
HT_MONEY_CHANGE_TYPE_TRADING = 6	-- 交易
-- 货币变化原因类型
MONEY_CHANGE_TYPE_CHARGE = 0	-- 玩家充值
MONEY_CHANGE_TYPE_NPC_BUY = 1	-- NPC购买
MONEY_CHANGE_TYPE_STALL_BUY = 2	-- 摊位购买
MONEY_CHANGE_TYPE_STALL_SALE = 3	-- 摊位卖出
MONEY_CHANGE_TYPE_TRADE = 4	-- 玩家交易
MONEY_CHANGE_MAIL = 5	-- 邮件
MONEY_CHANGE_QUEST = 6	-- 任务奖励
MONEY_CHANGE_DEAD = 7	-- 死亡掉落
MONEY_CHANGE_RIHUAN = 8	-- 日环
MONEY_CHANGE_USE_ITEM = 9	-- 预留
MONEY_CHANGE_GIFT_PACKS = 10	-- 系统礼包赠送
MONEY_CHANGE_NPC_SELL = 11	-- NPC出售
MONEY_CHANGE_ITEM_REPAIR = 12	-- 预留
MONEY_CHANGE_ITEM_APPRAISAL = 13	-- 预留
MONEY_CHANGE_NPC_REPURCHASE = 14	-- NPC回购
MONEY_CHANGE_GM_COMMAND = 15	-- GM招财命令
MONEY_CHANGE_CREATE_FACTION = 16	-- 创建帮派
MONEY_CHANGE_WAREHOUSE_HANLD = 17	-- 仓库操作
MONEY_CHANGE_SELECT_LOOT = 18	-- 战利品
MONEY_CHANGE_ACTIVITY = 19	-- 活动奖励
MONEY_CHANGE_TYPE_CHARGE_2 = 20	-- 充值额外赠送
MONEY_CHANGE_TYPE_CHARGE_3 = 21	-- 管理员扣除
MONEY_CHANGE_TYPE_CHARGE_4 = 22	-- 手动赠送
MONEY_CHANGE_USE_LABA = 23	-- 使用喇叭
MONEY_CHANGE_BAG_EXTENSION = 24	-- 背包扩展
MONEY_CHANGE_ITEM_BLEND = 25	-- 物品合成消耗铜钱
MONEY_CHANGE_SEVEN_DAY_GIFT = 26	-- 连登礼包
MONEY_CHANGE_CLEAR_PK_VALUE = 27	-- 使用元宝洗白
MONEY_CHANGE_JHM_REWARD = 28	-- 激活码奖励
MONEY_CHANGE_ONLINE_GIFT = 29	-- 每日在线奖励
MONEY_CHANGE_SPELL_UP = 30	-- 技能升阶
MONEY_CHANGE_USE_BOX = 31	-- 使用宝箱消耗
MONEY_CHANGE_BOX_OPEN = 32	-- 开宝箱获得
MONEY_CHANGE_BOX_RANDOM = 33	-- 开宝箱随机奖励
MONEY_CHANGE_JINGJIE = 34	-- 升级境界消耗
MONEY_CHANGE_SHENBING_BUY = 35	-- 神兵购买
MONEY_CHANGE_BUY_ATUO_RESPAWN = 36	-- 购买还魂丹自动复活
MONEY_CHANGE_FUBEN_KILLALL = 37	-- 副本全图秒杀消耗
MONEY_CHANGE_FUBEN_EWAI = 38	-- 副本额外奖励
MONEY_CHANGE_FUBEN_BUY = 39	-- 购买副本次数消耗
MONEY_CHANGE_FSZL_REWARD = 40	-- 飞升之路奖励
MONEY_CHANGE_PRESTIGE = 41	-- 活跃度
MONEY_CHANGE_PANTAO_CAIJI = 42	-- 采集蟠桃获得
MONEY_CHANGE_LINGKUANG_CAIJI = 43	-- 采集灵矿获得	
MONEY_CHANGE_QIYU_ZHUOYAO = 44	-- 扑捉妖魂消耗
MONEY_CHANGE_RESET_FORGE_ADD = 45	-- 重置锻造加成时间
MONEY_CHANGE_WABAO = 46	-- 挖宝获得
MONEY_CHANGE_HONGYAN_BUY_HUOLI = 47	-- 红颜购买活力
MONEY_CHANGE_HONGYAN_SHIJIAN = 48	-- 红颜事件获得
MONEY_CHANGE_HONGYAN_BUY_FASHION = 49	-- 红颜购买时装
MONEY_CHANGE_FORGE_STRENG = 50	-- 锻造强化
MONEY_CHANGE_FORGE_JINGLIAN = 51	-- 锻造精炼
MONEY_CHANGE_LINGDI_ZHAOMU = 52	-- 领地招募
MONEY_CHANGE_LINGDI_XUANSHANG = 53	-- 领地悬赏
MONEY_CHANGE_LINGDI_MIJING = 54	-- 领地秘境
MONEY_CHANGE_WUJIANG_REFRESH_PUB = 55	-- 元宝刷新酒馆武将
MONEY_CHANGE_FENGLIUZHEN_PUB_AUCTION = 56	-- 风流镇酒馆竞拍
MONEY_CHANGE_WUJIANG_QINGJIU = 55	-- 元宝清酒武将
MONEY_CHANGE_LINGDI_ZHENGBING = 56	-- 领地征兵
MONEY_CHANGE_FENGLIUZHEN_ZHUANPAN_ENTER = 57	-- 风流镇转盘进去房间
MONEY_CHANGE_USE_SPELL = 58	-- 使用技能
MONEY_CHANGE_UP_ASSISTSPELL = 59	-- 升级辅助技能
MONEY_CHANGE_LINGDI_BUY_BINGLI = 60	-- 领地征兵购买兵力
MONEY_CHANGE_WUJIANG_ZHENGZHAN = 61	-- 武将征战
MONEY_CHANGE_BUY_JUNLLING = 62	-- 购买军令
MONEY_CHANGE_SELL_WUJIANG_EQUIP = 63	-- 出售武将装备
MONEY_CHANGE_FENGLIUZHEN_KAOZHUANGYUAN = 64	-- 考状元奖励
MONEY_CHANGE_ZHUBO_SEND_GIFTS = 65	-- 主播送礼消耗
MONEY_CHANGE_ZHUBO_GRAB_SOFA = 66	-- 主播抢沙发
MAX_MONEY_CHANGE_TYPE = 67
-- 特殊包裹类型
BAG_VIRTUAL_TYPE_STALL = -1	-- 摆摊
BAG_VIRTUAL_TYPE_UNKNOWN = -2	-- 未知
SPECIALL_BAG_TYPE_MAIL = -3	-- 邮件
-- 物品类型
ITEM_TYPE_NONE = 0	-- 无
ITEM_TYPE_EQUIP = 1	-- 装备
ITEM_TYPE_BOX = 2	-- 宝箱类（使用获得道具类型的物品）
ITEM_TYPE_MATERIAL = 3	-- 材料
ITEM_TYPE_MEDICINE = 4	-- 药品
ITEM_TYPE_BUFF = 5	-- 获得buff型
ITEM_TYPE_SHELI = 6	-- 舍利
ITEM_TYPE_PK_MEDICINE = 7	-- PK药品
ITEM_TYPE_PET_MEDICINE = 8	-- 宠物药
ITEM_TYPE_NUMBER = 9	-- 数值类型
--  masks for ITEM_INT_FIELD_FLAGS field
ITEM_FLAGS_QUEST = 0	--  是否任务物品
ITEM_FLAGS_RMB = 1	-- 是否RMB物品
ITEM_FLAGS_APPRAISAL = 2	-- 是否鉴定
ITEM_FLAGS_BROKEN = 3	--  是否损坏的,耐久0
ITEM_FLAGS_USABLE = 4	--  是否可用的
ITEM_FLAGS_LOCKED = 5	--  物品锁定标志
ITEM_FLAGS_REFUNDABLE = 6	--  可回购的
ITEM_FLAGS_UNIQUE_EQUIPPED = 7	-- 是否独特装备
ITEM_FLAGS_SPECIALUSE = 8	--  特殊用途
ITEM_FLAGS_BOP_TRADEABLE = 9	-- 是否可交易的
ITEM_FLAGS_IS_BINDED = 10	-- 是否绑定
ITEM_FLAGS_IS_JIPIN = 11	-- 是否极品装备
-- 物品使用对象类型
ITEM_USE_SELF = 0	-- 自己
ITEM_USE_TARGET = 1	-- 目标
ITEM_USE_NULL = 2	-- 不可使用
-- 物物品使用结果类型
ITEM_USE_RESULT_DISAPPEAR = 0	-- 消失
ITEM_USE_RESULT_NOT_DISAPPEAR = 1	-- 不消失
ITEM_USE_RESULT_SUB_DURABLE = 2	-- 减少耐久
ITEM_USE_RESULT_UN_USE = 3	-- 不可使用
-- 道具返还类型
LOG_ITEM_RETURN_TYPE_HAVE = 0	-- 返还背包得到
LOG_ITEM_RETURN_TYPE_LOSE = 1	-- 返还背包失去
LOG_ITEM_RETURN_TYPE_CLEAR = 2	-- 返还背包清理
LOG_ITEM_RETURN_TYPE_GOLD = 3	-- 材料不足自动购买
-- 坐骑状态
MOUNT_STATE_FREE = 0	-- 空闲
MOUNT_STATE_WAS_RIDING = 1	-- 骑乘
-- 任务状态
QUEST_STATUS_NONE = 0	--  
QUEST_STATUS_COMPLETE = 1	-- 完成
QUEST_STATUS_UNAVAILABLE = 2	-- 得不到的，没空的，不能利用的???
QUEST_STATUS_INCOMPLETE = 3	-- 不完全,未完成
QUEST_STATUS_AVAILABLE = 4	-- 有效，可接受
QUEST_STATUS_FAILED = 5	-- 失败
MAX_QUEST_STATUS = 6
BOOK_STATUS_NONE = 0
BOOK_STATUS_COMPLETE = 1	-- 完成未领奖
BOOK_STATUS_UNAVAILABLE = 2	-- 得不到的，没空的，不能利用的
BOOK_STATUS_INCOMPLETE = 3	-- 不完全,未完成
BOOK_STATUS_AVAILABLE = 4	-- 有效，可接受
BOOK_STATUS_FAILED = 5	-- 失败
BOOK_STATUS_REWARDED = 6	-- 已领奖
-- 任务给予者状态
DIALOG_STATUS_NONE = 0
DIALOG_STATUS_UNAVAILABLE = 1	--  任务给予者状态,忙碌
DIALOG_STATUS_CHAT = 2	--  对话,3.1 - may be changed
DIALOG_STATUS_INCOMPLETE = 5	--   未完成
DIALOG_STATUS_REWARD_REP = 6	--  可重复领取奖励
DIALOG_STATUS_AVAILABLE_REP = 7	--  可重复接受任务
DIALOG_STATUS_AVAILABLE = 8	--  有可接任务
DIALOG_STATUS_REWARD2 = 9	--  no yellow dot on minimap
DIALOG_STATUS_REWARD = 10	--  报酬，报答，赏金,yellow dot on minimap
MAX_DIALOG_STATUS = 11
-- 任务标志
--  Flags used at server and sent to client	
QUEST_FLAGS_COMMIT_NOT_NEED_NPC = 256	--  提交任务是否校验npc
QUEST_FLAGS_ACCEPT_NOT_NEED_NPC = 512	--  接受任务是否校验npc
QUEST_FLAGS_DAILY = 1024	-- 日常任务 Used to know quest is Daily one
QUEST_FLAGS_AUTO_FAIL_OFF = 1	-- 离线或者死亡或者跨系列图传送后直接任务失败
QUEST_FLAGS_AUTO_COMPLETE = 16	-- auto complete	
QUEST_FLAGS_AUTO_REWARDED = 32	-- 自动奖励 These quests are automatically rewarded on quest complete and they will never appear in quest log client side.
QUEST_FLAGS_AUTO_ACCEPT = 64	-- quests in starting areas
QUEST_FLAGS_MANUAL = 128	-- 手动完成	
QUEST_FLAGS_CANREMOVE = 4096	-- 允许放弃
--  Mangos flags for set SpecialFlags in DB if required but used only at server
QUEST_FLAGS_FLAGS_REPEATABLE = 65536	-- 可重复接受的 Set by 1 in SpecialFlags from DB
QUEST_FLAGS_FLAGS_EXPLORATION_OR_EVENT = 131072	-- Set by 2 in SpecialFlags from DB (if required area explore, spell SPELL_EFFECT_QUEST_COMPLETE casting, table `*_script` command SCRIPT_COMMAND_QUEST_EXPLORED use, set from script DLL)
QUEST_FLAGS_FLAGS_DB_ALLOWED = 65535
--  Mangos flags for internal use only
QUEST_FLAGS_FLAGS_DELIVER = 262144	-- Internal flag computed only,需要收集物品的
QUEST_FLAGS_FLAGS_SPEAKTO = 524288	-- Internal flag computed only,需要与NPC对话的
QUEST_FLAGS_FLAGS_KILL_OR_CAST = 1048576	-- Internal flag computed only,杀死怪物或者使用任务物品的
QUEST_FLAGS_FLAGS_TIMED = 2097152	-- 定时?Internal flag computed only
QUEST_FLAGS_FLAGS_BUY_ITEM = 4194304	-- 购买物品的任务
QUEST_FLAGS_FLAGS_OPT_SYS = 8388608	-- 操作系统的任务
QUEST_FLAGS_FLAGS_LEVEL_CREATURE = 16777216	-- 杀等级怪
QUEST_FLAGS_FLAGS_LEVEL_PLAYER = 33554432	-- 杀等级玩家
QUEST_RELATION_TYPE_START = 0	-- 待接任务
QUEST_RELATION_TYPE_END = 1	-- 待交任务
-- 任务更新操作
QUEST_UNCHANGED = 0	-- 未变化
QUEST_CHANGED = 1	-- 变化
QUEST_NEW = 2
-- 战斗状态
COMBAT_STATE_LEAVE = 0	-- 脱离战斗
COMBAT_STATE_ENTER = 1	-- 进入战斗
-- 战斗状态
UNIT_STAT_DIED = 1
UNIT_STAT_MELEE_ATTACKING = 2	--  player is melee attacking someone
UNIT_STAT_CAST_SPELL = 4	--  引导技能
UNIT_STAT_SPELL_PROCESS = 8	-- 持续施法
UNIT_STAT_ROAMING = 16	-- 漫游
UNIT_STAT_CHASE = 32	-- 追逐
UNIT_STAT_SEARCHING = 64	-- 搜索
UNIT_STAT_FLEEING = 128	-- 逃避
UNIT_STAT_IN_FLIGHT = 256	--  player is in flight mode
UNIT_STAT_FOLLOW = 512	-- 跟随
UNIT_STAT_ROOT = 1024	-- 缠绕???
UNIT_STAT_CONFUSED = 2048	-- 使困惑
UNIT_STAT_DISTRACTED = 4096	-- 转移,使分心
UNIT_STAT_ISOLATED = 8192	--  隔离,光环无法影响其他玩家 area auras do not affect other players
UNIT_STAT_ATTACK_PLAYER = 16384	--  攻击
UNIT_STAT_ALL_STATE = 65535	-- (UNIT_STAT_STOPPED | UNIT_STAT_MOVING | UNIT_STAT_IN_COMBAT | UNIT_STAT_IN_FLIGHT)
-- 生存状态
DEATH_STATE_ALIVE = 0	-- 活着
DEATH_STATE_CORPSE = 1	-- 尸体，在客户端可见尸体
DEATH_STATE_DEAD = 2	-- 死亡，在客户端尸体消失
-- 击打信息，例如吸收，致命一击等等
HITINFO_NORMALSWING = 1	-- 普通
HITINFO_CRITHIT = 2	-- 暴击
HITINFO_MISS = 3	-- 躲避
HITINFO_GEDANG = 4	-- 格挡
HITINFO_CRITICALHIT = 5	-- 会心一击
HITINFO_BLOWFLY = 6	-- 击飞
HITINFO_LIUXUE = 7	-- 流血
HITINFO_CURE = 8	-- 治疗
HITINFO_JUMP_EVA = 9	-- 跳闪
HITINFO_POISON = 10	-- 毒
HITINFO_ICE = 11	-- 冰
HITINFO_FANTANSHANGHAI = 12	-- 反弹伤害
-- 移动状态
MOVE_STATUS_STOP = 0
MOVE_STATUS_RUN = 1
-- NPC标识
-- / Non Player Character flags
UNIT_NPC_FLAG_NONE = -1
UNIT_NPC_FLAG_GOSSIP = 0	--  100%闲聊NPC
UNIT_NPC_FLAG_QUESTGIVER = 1	--  任务发布PCguessed, probably ok
UNIT_NPC_FLAG_UNK1 = 2	-- 预留
UNIT_NPC_FLAG_UNK2 = 3
UNIT_NPC_FLAG_TRAINER = 4	--  100%  训练师
UNIT_NPC_FLAG_TRAINER_CLASS = 5	--  100%  职业训练师
UNIT_NPC_FLAG_TRAINER_PROFESSION = 6	--  100%  自由职业训练师？
UNIT_NPC_FLAG_VENDOR = 7	--  100%  买卖商人
UNIT_NPC_FLAG_VENDOR_PROP = 8	--  100%, 道具
UNIT_NPC_FLAG_VENDOR_WEAPON = 9	--  100%  武器
UNIT_NPC_FLAG_VENDOR_POISON = 10	--  药品
UNIT_NPC_FLAG_VENDOR_REAGENT = 11	--  100%  饰品
UNIT_NPC_FLAG_VENDOR_EQUIPMENT = 12	--  100%  装备
UNIT_NPC_FLAG_FLIGHTMASTER = 13	--  100% 飞行点管理员
UNIT_NPC_FLAG_SPIRITHEALER = 14	--  guessed 复活Npc
UNIT_NPC_FLAG_SPIRITGUIDE = 15	--  guessed 灵魂向导
UNIT_NPC_FLAG_INNKEEPER = 16	--  100% 旅店老板
UNIT_NPC_FLAG_WAREHOUSE = 17	--  100% 仓库
UNIT_NPC_FLAG_PETITIONER = 18	--  100% 竞技场
UNIT_NPC_FLAG_TABARDDESIGNER = 19	--  100%工会徽章设计NPC
UNIT_NPC_FLAG_BATTLEMASTER = 20	--  100%战场管理员
UNIT_NPC_FLAG_AUCTIONEER = 21	--  100%拍卖商
UNIT_NPC_FLAG_STABLEMASTER = 22	--  100%马夫
UNIT_NPC_FLAG_GUILD_BANKER = 23	--  公会银行cause client to send 997 opcode
UNIT_NPC_FLAG_CHALLENGE = 24	--  神奇的挑战怪要变大变粗,UNIT_NPC_FLAG_GUARD
UNIT_NPC_FLAG_ONE_ONE = 25	--  是否光棍怪,没钱，没精验，没装备，没次数
-- 所有BUFF buff id要与表buff_template_table的id对应
BUFF_ONEPOINTFIVE_JINGYAN = 101	-- 1.5倍经验丹
BUFF_TOW_JINGYAN = 102	-- 2倍经验丹
BUFF_THREE_JINGYAN = 103	-- 3倍经验丹
BUFF_FIVE_JINGYAN = 104	-- 5倍经验丹
BUFF_FANTAN = 105	-- 反弹
BUFF_LIANJIE = 106	-- 连接
BUFF_BEILIANJIE = 107	-- 被连接
BUFF_GANGCI = 108	-- 钢刺
BUFF_DINGSHEN = 109	-- 定身
BUFF_YUNXUAN = 110	-- 晕眩
BUFF_YUNMIE_ELING = 111	-- 陨灭（恶灵）
BUFF_HUIFU_HUDUN = 112	-- 恢复护盾
BUFF_FANJI_HUDUN = 113	-- 反击护盾
BUFF_LINGXUE = 114	-- 流血
BUFF_ZHUOSHAO = 115	-- 灼烧
BUFF_JUDU = 116	-- 剧毒
BUFF_ZHONGDU = 117	-- 中毒
BUFF_BINGJIA = 118	-- 冰甲
BUFF_BINGDONG = 119	-- 冰冻
BUFF_BAOZHA_DILEI = 120	-- 爆炸（地雷）
BUFF_SHOUWEI_ZHAOHUAN = 121	-- 守卫（召唤）
BUFF_BIAOJI = 122	-- 标记
BUFF_KUANGBAO = 123	-- 狂暴
BUFF_JIANSU = 124	-- 减速
BUFF_CHENMO = 125	-- 沉默
BUFF_XUECHI = 126	-- 血池
BUFF_WAIGONGMIANYI = 127	-- 外攻免疫
BUFF_NEIGONGMIAN = 128	-- 内攻免疫
BUFF_WUDI = 129	-- 无敌
BUFF_ZHANSHEN_FUTI = 130	-- 战神附体
BUFF_JINGANG_BUHUAITI = 131	-- 金刚不坏体
BUFF_KUANGBEN = 132	-- 狂奔
BUFF_HUOBA = 133	-- 火把
BUFF_LINGTI = 134	-- 灵体
BUFF_HUANHUA_ZHU = 135	-- 幻化成猪
BUFF_HUANHUA_REN = 136	-- 幻化成人
BUFF_HUANHUA_GUI = 137	-- 幻化成鬼
BUFF_HUANHUA_XIAN = 138	-- 幻化成仙
BUFF_HUANHUA_XIULUO = 139	-- 幻化成修罗
BUFF_XIULUOLI = 140	-- 修罗力
BUFF_ZHENYING = 141	-- 阵营
BUFF_ZHANDOU_STATE = 142	-- 战斗状态
BUFF_JUMP_JUMP = 143	-- 跳跃
BUFF_JUMP_DOWN = 144	-- 身轻
BUFF_ANXIANG_SHUYING = 145	-- 暗香疏影
BUFF_ZHIKONG = 146	-- 滞空
BUFF_FUKONG = 147	-- 浮空
MAX_2JI_SHIJIAN_UINT32 = 20	-- 红颜2级事件uint32
MAX_HONGYAN_DATI_COUNT = 10	-- 红颜最大答题次数
-- 红颜系统操作枚举
HONGYAN_JIESHI_MEIREN = 0	-- --结识美人
HONGYAN_DIANZAN = 1	-- --点赞
HONGYAN_PINGJIA = 2	-- --评价
HONGYAN_SHIZHUANG_JIHUO = 3	-- --时装激活
HONGYAN_SHIZHUANG_CHUANDAI = 4	-- --时装穿戴
HONGYAN_XIANGCE_JIHUO = 5	-- --相册激活
HONGYAN_SHIJIAN_CHULI = 6	-- --事件处理
HONGYAN_CHUYOU = 7	-- --出游
HONGYAN_HUIFU_HUOLI = 8	-- --恢复活力值
HONGYAN_ADD_NEIWU_SHIJIAN = 9	-- --增加内务事件
-- 红颜系统玩家属性
HONGYAN_PLAYER_ATTRS_XIAYI = 0	-- --侠义值
HONGYAN_PLAYER_ATTRS_FENGLIU = 1	-- --风流
HONGYAN_PLAYER_ATTRS_MINGSHENG = 2	-- --名声
HONGYAN_PLAYER_ATTRS_WENTAO = 3	-- --文韬
HONGYAN_PLAYER_ATTRS_WULUE = 4	-- --武略
HONGYAN_PLAYER_ATTRS_CAIYI = 5	-- --才艺
HONGYAN_PLAYER_ATTRS_QINHE = 6	-- --亲和
HONGYAN_PLAYER_ATTRS_LIYI = 7	-- --礼仪
HONGYAN_PLAYER_ATTRS_XIANGMAO = 8	-- --相貌
HONGYAN_PLAYER_ATTRS_HUOLI = 9	-- --活力
MAX_PLAYER_ATTRS = 10
-- 红颜系统美人属性
HONGYAN_MEIREN_ATTRS_JIESHI_BIT = 0	-- 0:是否结识  1~31：结识条件
HONGYAN_MEIREN_ATTRS_XINGGE_BIT = 1	-- 性格
HONGYAN_MEIREN_ATTRS_AIHAO_BIT = 2	-- 爱好
HONGYAN_MEIREN_ATTRS_CHANGJING_BIT = 3	-- 场景
HONGYAN_MEIREN_ATTRS_SHIZHUANG_BIT = 4	-- 时装
HONGYAN_MEIREN_QINMIDU_UINT16 = 5	-- 0：亲密度 1:当前穿戴的时装ID
HONGYAN_MEIREN_XIANGCE_BIT = 6	-- 美人激活的相册
MAX_MEIREN_ATTRS_TYPE = 7
-- 红颜系统美人人气值
HONGYAN_MEIREN_DIANZAN = 0	-- 点赞
HONGYAN_MEIREN_MEIHAO = 1	-- 美貌
HONGYAN_MEIREN_JIESHI_COUNT = 2	-- 美人结识的玩家数量
MAX_MEIREN_RENQI_TYPE = 3
-- 红颜系统美人表
HONGYAN_CAIXUE = 0	-- 采雪
HONGYAN_ZHENFEI = 1	-- 珍妃
HONGYAN_YANLIN = 2	-- 燕琳
HONGYAN_MURONGYANYAN = 3	-- 慕容嫣嫣
HONGYAN_YAORU = 4	-- 瑶如
HONGYAN_XIANGJING = 5	-- 项晶
HONGYAN_HENGXIAOZHUO = 6	-- 桓小卓
HONGYAN_LIJI = 7	-- 俪姬
HONGYAN_SIQI = 8	-- 思绮
HONGYAN_YOUYOU = 9	-- 幽幽
HONGYAN_LINCHUER = 10	-- 林楚儿
HONGYAN_WANYAN_YUNNA = 11	-- 完颜云娜
HONGYAN_QUANHUIQIAO = 12	-- 全慧乔
HONGYAN_TUOBALVZHU = 13	-- 拓跋绿珠
HONGYAN_QINGYAN = 14	-- 轻颜
HONGYAN_SUOMOER = 15	-- 索沫儿
HONGYAN_GUQIANQIAN = 16	-- 谷纤纤
HONGYAN_AYIGULI = 17	-- 阿依古丽
HONGYAN_ZUOYUYI = 18	-- 左玉怡
HONGYAN_ZILUO = 19	-- 紫罗
HONGYAN_QUNUO = 20	-- 曲诺
HONGYAN_XUANYING = 21	-- 玄樱
MAX_MEIREN = 32
-- 所有GM命令的定义
GM_COMMAND_NULL = 0	-- 空命令
GM_COMMAND_JIULONGCHAO = 1	-- @天书世界
GM_COMMAND_SUCAI = 2	-- @素材
GM_COMMAND_JIAOBEN = 3	-- @脚本
GM_COMMAND_TI = 4	-- @踢
GM_COMMAND_ZAIXIAN = 5	-- @在线
GM_COMMAND_DITURENSHU = 6	-- @地图人数
GM_COMMAND_ZHAOCAI = 7	-- @招财
GM_COMMAND_ZHIZAO = 8	-- @制造
GM_COMMAND_QINGLI = 9	-- @清理
GM_COMMAND_ZHUANGBEI = 10	-- @装备
GM_COMMAND_PAIHANGBANG = 12	-- @排行榜
GM_COMMAND_YOUJIAN = 13	-- @邮件
GM_COMMAND_BENGDIAO = 15	-- @崩掉
GM_COMMAND_BANGZHU = 16	-- @帮助
GM_COMMAND_GONGGAO = 17	-- @公告
GM_COMMAND_SHIJIETISHI = 18	-- @世界提示
GM_COMMAND_PAIDUI = 19	-- @排队
GM_COMMAND_PINGBICI = 20	-- @屏蔽词
GM_COMMAND_GUANBIFUWUQI = 21	-- @关闭服务器
GM_COMMAND_CHONGZHI = 22	-- @充值
GM_COMMAND_GUANBIDITU = 23	-- @关闭地图
GM_COMMAND_DENGJI = 24	-- @等级
GM_COMMAND_QINGLIRENWUWUPIN = 25	-- @清理任务物品
GM_COMMAND_QINGLIRENWU = 26	-- @清理任务
GM_COMMAND_WANCHENGRENWU = 27	-- @完成任务
GM_COMMAND_JIESHOURENWU = 28	-- @接受任务
GM_COMMAND_GANDIAO = 29	-- @干掉
GM_COMMAND_SHUAGUAI = 30	-- @刷怪
GM_COMMAND_CHUANSONG = 31	-- @传送
GM_COMMAND_XIAZOU = 32	-- @瞎走
GM_COMMAND_SUICIDE = 33	-- @自爆
GM_COMMAND_SERVER_INFO = 34	-- @服务器
GM_COMMAND_DB = 35	-- @数据库
GM_COMMAND_KAIFUSHIJIAN = 36	-- @开服时间
GM_COMMAND_TEST_SHUJU = 37	-- @测试数据
GM_COMMAND_UPDATE_SERVER = 38	-- @更新服务器
GM_COMMAND_RESESSION_OPTS = 39	-- @协议注册
GM_COMMAND_RENWUTIAOZHUAN = 40	-- @任务跳转
GM_COMMAND_BACKUP_DATA = 41	-- @备份数据
GM_COMMAND_RETURN_DATA = 42	-- @回档数据
GM_COMMAND_PRINT_OBJECT = 43	-- @打印对象
GM_COMMAND_TEST_HEFU = 44	-- @测试合服
GM_COMMAND_CLEAR_PAIHANGBANG = 45	-- @清空排行榜
GM_COMMAND_MEMORY_RECOVERY = 46	-- @内存回收
GM_COMMAND_PRINT_MAP = 47	-- @打印地图
GM_COMMAND_DEL_MAP_INFO = 48	-- @清空地图信息
GM_COMMAND_RESTORE_SYSTEM = 49	-- @后台命令
GM_COMMAND_CALL_REMOVE_ITEM = 50	-- @清空物品监听
GM_COMMAND_SUBLINE = 51	-- @分线
-- 查询玩家信息的时候，需要附带的信息
QUERY_PLAYER_FLAG_BASE = 0	-- 玩家基础信息
QUERY_PLAYER_FLAG_NAME = 1	-- 玩家姓名
QUERY_PLAYER_FLAG_EQUIP = 2	-- 玩家装备形象
QUERY_PLAYER_FLAG_PIFENG = 3	-- 披风信息
QUERY_PLAYER_FLAG_FORCE = 4	-- 玩家战斗力
QUERY_PLAYER_FLAG_OTHER = 5	-- 其它信息
-- 下面是非玩家下标的东西
QUERY_PLAYER_FLAG_MOUNT = 20	-- 所有坐骑
QUERY_PLAYER_FLAG_EQUIP_BAG = 21	-- 装备包裹
QUERY_PLAYER_FLAG_MAIN_BAG = 22	-- 背包包裹
QUERY_PLAYER_FLAG_STORAGE_BAG = 23	-- 仓库包裹
QUERY_PLAYER_FLAG_STALL_BAG = 24	-- 摊位包裹	
-- 任务类型定义
QUEST_TYPE_MAIN = 0	-- 主线任务
QUEST_TYPE_EXTENSIONS = 1	-- 支线任务
QUEST_TYPE_ZHUANSHENG = 2	-- 转生任务
QUEST_TYPE_XUANSHANG = 3	-- 悬赏任务
QUEST_TYPE_RIHUAN = 4	-- 日环任务
-- 货币处理类型
CURRENCY_HANDLE_TYPE_ADD = 0	-- 增加
CURRENCY_HANDLE_TYPE_SUB = 1	-- 减少
-- 技能有效时间技能ID枚举
SPELL_VALID_TIME_POTIAN_2 = 0	-- 破天二式
SPELL_VALID_TIME_POTIAN_3 = 1	-- 破天三式
SPELL_VALID_TIME_YUNFEI_2 = 2	-- 云飞玉皇·二段
SPELL_VALID_TIME_YUNFEI_3 = 3	-- 云飞玉皇·三段
SPELL_VALID_TIME_FENGFAN_2 = 4	-- 风翻云变·二段
SPELL_VALID_TIME_ZHUXIAN_2 = 5	-- 诛仙剑阵·二段
SPELL_VALID_TIME_ZHUXIAN_3 = 6	-- 诛仙剑阵·三段
MAX_SPELL_VALID = 15
MAX_SPELL_SLOT = 6
NOMAL_ATTACK_TIME = 1300
NOMAL_MOVE_SPEED = 130
MAX_ITEM_SPELL = 3
MAX_BASE_ATTR_FIELD_COUNT = 15	-- 附加属性最大条数
MAX_BUFF = 50	-- 玩家身上最大buff数
MAX_UNIT_BUFF = 16	-- 精灵身上最大buff数
-- 装备类型包括时装 从头到脚
-- 普通装备
EQUIPMENT_TYPE_MAIN_WEAPON = 0	-- 武器
EQUIPMENT_TYPE_HELMET = 1	-- 头盔
EQUIPMENT_TYPE_COAT = 2	-- 衣服
EQUIPMENT_TYPE_BELT = 3	-- 腰带
EQUIPMENT_TYPE_LEG = 4	-- 护腕
EQUIPMENT_TYPE_PANTS = 5	-- 裤子
EQUIPMENT_TYPE_SHOES = 6	-- 鞋子
EQUIPMENT_TYPE_BRACELET = 7	-- 玉佩
EQUIPMENT_TYPE_NECKLACE = 8	-- 项链
EQUIPMENT_TYPE_LRING = 9	-- 左戒指
EQUIPMENT_TYPE_CLOAK = 10	-- 披风
EQUIPMENT_TYPE_RRING = 11	-- 右戒指
EQUIPMENT_TYPE_RESERVE2 = 12	-- 预留
EQUIPMENT_TYPE_RESERVE3 = 13	-- 预留
EQUIPMENT_TYPE_RESERVE4 = 14	-- 预留
EQUIPMENT_TYPE_RESERVE5 = 15	-- 预留
EQUIPMENT_TYPE_RESERVE6 = 16	-- 预留
EQUIPMENT_TYPE_RESERVE7 = 17	-- 预留
EQUIPMENT_TYPE_RESERVE8 = 18	-- 预留
EQUIPMENT_TYPE_RESERVE9 = 19	-- 预留
EQUIPMENT_TYPE_MAX_POS = 20	-- 最大位置
-- 时装类型接在普通装备后面 从头到脚
FASHION_TYPE_MAIN_WEAPON = 20	-- 头盔 预留
FASHION_TYPE_HELMET = 21	-- 耳坠
FASHION_TYPE_COAT = 22	-- 项链
FASHION_TYPE_BELT = 23	-- 披风
FASHION_TYPE_LEG = 24	-- 护肩 预留
FASHION_TYPE_PANTS = 25	-- 衣服
FASHION_TYPE_SHOES = 26	-- 主手武器
FASHION_TYPE_BRACELET = 27	-- 副手武器
FASHION_TYPE_NECKLACE = 28	-- 手镯 
FASHION_TYPE_RING = 29	-- 腰带
FASHION_TYPE_CLOAK = 30	-- 护手
FASHION_TYPE_RESERVE1 = 31	-- 裤子 预留
FASHION_TYPE_RESERVE2 = 32	-- 鞋子 预留
FASHION_TYPE_RESERVE3 = 33	-- 特殊武器时装,现作为无双方天戟下标
FASHION_TYPE_RESERVE4 = 34	-- 指环
FASHION_TYPE_RESERVE5 = 35	-- 玉玺
FASHION_TYPE_RESERVE6 = 36	-- 结婚戒指
FASHION_TYPE_RESERVE7 = 37	-- 护符左
FASHION_TYPE_RESERVE8 = 38	-- 护符右
FASHION_TYPE_RESERVE9 = 39	-- 预留
MAX_EQUIPMENT_TYPE = 40	-- 最多可装备位置
-- 武器类型
WEAPON_POS_MAIN = 0	-- 主手
WEAPON_POS_OFF = 1	-- 副手
WEAPON_POS_SINGLE_HAND = 2	-- 单手
WEAPON_POS_BOTH_HANDS = 3	-- 双手
MAX_WEAPON_POS = 4	-- 不是武器
-- 能量类型,用于消耗
POWER_MANA = 0	-- 蓝,内力	
POWER_ENERGY = 1	-- 能量,体力	
MAX_POWERS = 2
-- 战斗计算过程中的各种百分比
COMBAT_RATE_CRIT = 0	-- 暴击率
COMBAT_RATE_EVA = 1	-- 闪避率
MAX_COMBAT_RATE = 2
-- 包裹类型
BAG_TYPE_MAIN_BAG = 0	-- 主包裹
BAG_TYPE_EQUIP = 1	-- 装备包裹
BAG_TYPE_STORAGE = 2	-- 仓库
BAG_TYPE_REPURCHASE = 3	-- 回购
BAG_TYPE_SYSTEM = 4	-- 系统包裹
BAG_TYPE_STALL = 5	-- 摊位包裹
BAG_TYPE_ZHUBO = 6	-- 主播包裹
MAX_BAG = 20	-- 预留20个
-- 背包扩展类型
BAG_EXTENSION_TYPE_AUTO = 0	-- 自动开启
BAG_EXTENSION_TYPE_GOLD = 1	-- 元宝开启
-- 安全码修改类型
SAFETY_CODE_MODIFY_TYPE_CODE = 0	-- 密码修改
SAFETY_CODE_MODIFY_TYPE_QUESTION = 1	-- 安全问题修改
-- 货币类型
MONEY_TYPE_GOLD_INGOT = 0	-- 元宝
MONEY_TYPE_BIND_GOLD = 1	-- 绑定元宝
MONEY_TYPE_SILVER = 2	-- 身上的银子
MONEY_TYPE_SILVER_WAREHOUSE = 3	-- 仓库的银子
MONEY_TYPE_GOLD_WAREHOUSE = 4	-- 仓库元宝
MONEY_TYPE_BIND_GOLD_WAREHOUSE = 5	-- 仓库的绑元
MAX_MONEY_TYPE = 12
-- 基本属性
BASE_ATTR_HP = 0	-- 基础生命
BASE_ATTR_OUT_DAMAGE = 1	-- 基础外攻
BASE_ATTR_IN_DAMAGE = 2	-- 基础内攻
BASE_ATTR_OUT_DEF = 3	-- 基础外防
BASE_ATTR_IN_DEF = 4	-- 基础内防
BASE_ATTR_HIT = 5	-- 基础命中
BASE_ATTR_EVA = 6	-- 基础闪避
BASE_ATTR_CRIT = 7	-- 基础暴击
BASE_ATTR_CRIT_DEF = 8	-- 基础抗暴
MAX_BASE_ATTR = 9
-- 应用服计算出来的属性枚举
-- 0用来当做无属性 约定基本属性放在枚举的最后面
EQUIP_ATTR_NONE = 0	-- 空属性
EQUIP_ATTR_HP = 1	-- 生命
EQUIP_ATTR_OUT_DAMAGE = 2	-- 外攻
EQUIP_ATTR_IN_DAMAGE = 3	-- 内攻
EQUIP_ATTR_OUT_DEF = 4	-- 外防
EQUIP_ATTR_IN_DEF = 5	-- 内防
EQUIP_ATTR_HIT = 6	-- 命中
EQUIP_ATTR_EVA = 7	-- 闪避
EQUIP_ATTR_CRIT = 8	-- 暴击
EQUIP_ATTR_CRIT_DEF = 9	-- 抗暴
EQUIP_ATTR_FIXED_HP = 10	-- 固定生命
EQUIP_ATTR_FIXED_OUT_DAMAGE = 11	-- 固定外攻
EQUIP_ATTR_FIXED_IN_DAMAGE = 12	-- 固定内攻
EQUIP_ATTR_FIXED_OUT_DEF = 13	-- 固定外防
EQUIP_ATTR_FIXED_IN_DEF = 14	-- 固定内防
EQUIP_ATTR_FIXED_HIT = 15	-- 固定命中
EQUIP_ATTR_FIXED_EVA = 16	-- 固定闪避
EQUIP_ATTR_FIXED_CRIT = 17	-- 固定暴击
EQUIP_ATTR_FIXED_CRIT_DEF = 18	-- 固定抗暴
EQUIP_ATTR_EVA_RATE = 19	-- 闪避率(百分比)
EQUIP_ATTR_CRIT_RATE = 20	-- 暴击率(百分比)
EQUIP_ATTR_POISON = 21	-- 毒属性
EQUIP_ATTR_ICE = 22	-- 冰属性
EQUIP_ATTR_ADD_OUT_DAMAGE = 23	-- 外攻伤害加深
EQUIP_ATTR_ADD_IN_DAMAGE = 24	-- 内攻伤害加深
EQUIP_ATTR_SUB_OUT_DAMAGE = 25	-- 外攻伤害减免
EQUIP_ATTR_SUB_IN_DAMAGE = 26	-- 内攻伤害减免
EQUIP_ATTR_BEAR = 27	-- 负重
EQUIP_ATTR_LUCKY = 28	-- 幸运
EQUIP_ATTR_MEILI = 29	-- 魅力
EQUIP_ATTR_PHYSICAL = 30	-- 体力
EQUIP_ATTR_MOVE_SPD = 31	-- 移动速度
MAX_EQUIP_ATTR = 32
-- 物品其他属性枚举（物品特殊属性接在MAX_EQUIP_ATTR后面）
ITEM_OTHER_ATTR_FAIL_TIME = 32	-- 失效时间
ITEM_OTHER_ATTR_STRONG_LV = 33	-- 强化等级
ITEM_OTHER_ATTR_STRONG_FAIL_COUNT = 34	-- 强化失败次数
ITEM_OTHER_ATTR_FORCE = 35	-- 战斗力
-- 技能槽技能
SLOT_SPELL_ID = 0	-- 技能槽技能id
SLOT_SPELL_CD = 1	-- 技能槽技能CD
SLOT_SPELL_LV = 2	-- 技能槽技能等级
MAX_SLOT_ATTR_COUNT = 3	-- 技能槽属性数量
-- 被动技能槽技能(槽的位置代表技能id)
SLOT_PASSIVE_SPELL_ID = 0	-- 技能槽技能CD
SLOT_PASSIVE_SPELL_CD = 1	-- 技能槽技能CD	
MAX_SLOT_PASSIVE_COUNT = 2	-- 技能槽属性数量
-- 技能族公共CD类型
SPELL_CD_BASE = 0
SPELL_CD_SPECIAL = 1
MAX_SPELL_CD_TYPE = 2
-- 任务槽 偏移量
QUEST_ID_OFFSET = 0
QUEST_STATE_OFFSET = 1
QUEST_COUNTS_OFFSET = 2
QUEST_COUNTS_OFFSET_1 = 3
QUEST_COUNTS_OFFSET_2 = 4
QUEST_COUNTS_OFFSET_3 = 5
QUEST_TIME_OFFSET = 6
QUEST_FLAG_OFFSET = 7	-- bit标志位 看定义QuestSlotFlags
MAX_QUEST_OFFSET = 8
QUEST_SLOT_FLAGS_REWARD = 0	-- 是否领取过任务奖励
QUEST_SLOT_FLAGS_EXPLORE = 1	-- 是否已探索
MAX_QUEST_LOG_SIZE = 32	-- 任务槽的上限
QUEST_OBJECTIVES_COUNT = 8	-- 物品数量或杀死生物的数量上限
QUEST_REWARD_CHOICES_COUNT = 6
QUEST_REWARDS_COUNT = 4
QUEST_LOW_LEVEL_HIDE_DIFF = 4
QUEST_ITEMS_COUNTS = 10	-- 任务物品最大容量
QUEST_COMPLETE_LIST = 200	-- 任务已完成列表的长度
MAX_PASSIVE_SPELL_COUNT = 30	-- 被动技能的上限
BINLOG_STRING_FIELD_GUID = 0	-- 所有binlog的guid位置
BINLOG_STRING_FIELD_NAME = 1	-- 所有binlog的name位置
BINLOG_STRING_FIELD_VERSION = 2	-- 所有binlog的版本信息位置
BINLOG_STRING_FIELD_OWNER = 3	-- 所有binlog的owner位置
-- 战利品下标
LOOT_PUBLIC_INT_START_POS = 0	-- grid开始坐标
LOOT_PUBLIC_INT_END_POS = 1	-- grid结束坐标
LOOT_PUBLIC_INT_BEGIN = 2	-- 战利品真正开始的下标
LOOT_PUBLIC_INT_ENTRY = 0	-- 战利品模板
LOOT_PUBLIC_INT_MONEY_SUM = 1	-- 金钱数量
MAX_LOOT_PUBLIC_INT_FIELD = 2
LOOT_PUBLIC_STR_OWNER = 0
MAX_LOOT_PUBLIC_STR_FIELD = 1
LOOT_PRIVATE_INT_FAIL_TIME = 0	-- 拾取以后的物品失效时间
LOOT_PRIVATE_INT_EXIST_TIME = 1	-- 战利品存活时间
LOOT_PRIVATE_INT_OWNER_TIME = 2	-- 战利品拥有者保护时间
LOOT_PRIVATE_INT_FLAG = 3	-- 标志位
MAX_LOOT_PRIVATE_INT_FIELD = 4
LOOT_PRIVATE_STRING_CREATE_BY = 0	-- 战利品掉落怪GUID
LOOT_PRIVATE_STRING_CREATE_NAME = 1	-- 战利品掉落怪名称
MAX_LOOT_PRIVATE_STRING = 2
LOOT_STR_FIELD_BEGIN = 4	-- 战利品字符串开始下标
-- 战利品标志位
LOOT_FLAG_GET_ITEM_NOTICE = 0	-- 拾起物品是否需要公告
LOOT_FLAG_ITEM_BIND = 1	-- 战利品是否绑定
-- 玩家能否做某事的flag偏移定义
UNIT_CANDO_OFFSET_TYPE_CANT_CAST = 0	-- 限制施法
UNIT_CANDO_OFFSET_TYPE_CANT_MOVE = 1	-- 限制移动
UNIT_FIELD_BYTE_0 = 0	-- 0:类型ID，1：死亡状态，2：移动速度，3：八卦阵等级
UNIT_FIELD_BYTE_1 = 1	-- 0：性别，1：阵营，2：种族，3：职业
UNIT_FIELD_BYTE_2 = 2	-- 0：灰名时间，1：付费等级，2：免费复活，3：玩家称号
UNIT_FIELD_BYTE_3 = 3	-- 0: 头像，1：发型，2：GM等级，3：攻击模式
UNIT_FIELD_BYTE_4 = 4	-- 0：预留，1：当前坐骑模板id，2：皮肤类型 3：预留
UNIT_FIELD_UINT16_0 = 5	-- 0：精灵模板，1：精灵等级
UNIT_FIELD_UINT16_1 = 6	-- 0：地图ID，1：跨服1v1连胜次数
UNIT_FIELD_UINT16_2 = 7	-- 0:玩家报名跨服时收到匹配信息中给的编号 1:身上宝物采集阵营编号
UNIT_FIELD_FLAGS = 8	-- 精灵身上的标志位
GO_FIELD_FLAGS = 9	-- 游戏对象的一些标识位
GO_FIELD_DATA = 10	-- 动态数据字段,目前保留为4个int
UNIT_FIELD_NPC_FLAG = 14	-- NPC标识
UNIT_FIELD_INSTANCE_ID = 15	-- 地图实例ID
UNIT_FIELD_HEALTH = 16	-- 当前生命	
UNIT_FIELD_MAXHEALTH = 17	-- 最大生命
UNIT_FIELD_EQUIPMENT_COAT = 18	-- 上衣模板
UNIT_FIELD_EQUIPMENT_MAIN_WEAPON = 19	-- 主手武器
UNIT_FIELD_BUFF = 20	-- BUFFID
-- 注意了：创建包需要下发的下标放在 UNIT_FIELD_BUFF前面,UNIT_FIELD_BUFF_TM后面的下标走订阅
UNIT_FIELD_BUFF_TM = 28	-- BUFF时间（掩码从这开始）
UNIT_FIELD_BUFF_RESERVE = 36	-- BUFF预留值
UNIT_FIELD_BUFF_LEVEL = 52	-- BUFF等级（byte）
UNIT_FIELD_BUFF_CASTER_GUID = 56	-- buff施法者guid
UNIT_FIELD_FORCE = 72	-- 战斗力
UNIT_FIELD_POWERS_ENERGY = 73	-- 当前体力
UNIT_FIELD_MAXPOWERS_ENERGY = 74	-- 最大体力
UNIT_FIELD_OUT_DAMAGE = 75	-- 外攻
UNIT_FIELD_IN_DAMAGE = 76	-- 内攻
UNIT_FIELD_OUT_RESISTANCES = 77	-- 外防
UNIT_FIELD_IN_RESISTANCES = 78	-- 内防
UNIT_FIELD_COMBAT_HIT = 79	-- 命中
UNIT_FIELD_COMBAT_CRIT = 80	-- 暴击
UNIT_FIELD_COMBAT_EVA = 81	-- 闪避
UNIT_FIELD_COMBAT_CRIT_DEF = 82	-- 抗暴
UNIT_FIELD_COMBAT_RATE_CRIT = 83	-- 暴击率
UNIT_FIELD_COMBAT_RATE_EVA = 84	-- 闪避率
UNIT_FIELD_POISON = 85	-- 毒
UNIT_FIELD_ICE = 86	-- 冰
UINT_FIELD_ADD_OUT_IN_DAMAGE = 87	-- 0:外攻伤害加深 1:内攻伤害加深
UINT_FIELD_SUB_OUT_IN_DAMAGE = 88	-- 0:外攻伤害减免 1:内攻伤害减免
UINT_FIELD_BOSS_DATA = 89	-- boss数据byte 0:boss状态 1:boss前一状态 2:boss索引(云游的是这个用途)
UINT_FIELD_BOSS_DATA1 = 90	-- boss数据byte 0:当前坐标x 1:当前坐标y 2:下一坐标x 3:下一坐标y(云游的是这个用途)
UNIT_FIELD_PASSIVE_SPELLID = 91	-- 被动技能ID
UNIT_FIELD_PASSIVE_SPELLCD = 106	-- 被动技能CD
UNIT_FIELD_PASSIVE_SPELLCD_END = 136	-- 被动技能CD
MAX_UNIT_FIELD = 137
GO_STRING_FIELD_CREATED_BY = 4
UNIT_STRING_FIELD_ALIAS_NAME = 5
MAX_UNIT_STRING_FIELD = 6
-- 游戏对象类型
GO_ENTRY_TELETEPORT = 1	-- 传送点
GO_ENTRY_LOOT = 9	-- 战利品游戏对象
-- 游戏对象数据
-- 传送点专用
GO_TELETEPORTER_TO_MAPID = 10
GO_TELETEPORTER_TO_X = 11
GO_TELETEPORTER_TO_Y = 12
-- 任务相关游戏对象
GO_QUEST_ID_0 = 10	-- 相关任务0
GO_QUEST_ID_1 = 11	-- 相关任务1
GO_QUEST_ID_2 = 12	-- 相关任务2
GO_QUEST_ID_3 = 13	-- 相关任务3
GO_STRING_FIELD_CREATED_NAME = 5	-- 战利品创建者Name
-- 机关类相关的
GO_GEAR_STATUS = 10	-- 机关状态
GO_GEAR_KILLER = 11	-- 机关破坏者
-- 机关状态枚举
GO_GEAR_STATUS_START = 1	-- 机关初始状态
GO_GEAR_STATUS_OPEN = 2	-- 机关打开
GO_GEAR_STATUS_CLOSE = 3	-- 机关关闭
GO_GEAR_STATUS_END = 4	-- 机关即将消失
-- 精灵身上标识下标枚举
UNIT_FIELD_FLAGS_CANT_CAST = 0	-- 标识是否可以施法
UNIT_FIELD_FLAGS_CANT_MOVE = 1	-- 标识是否可以移动
UNIT_FIELD_FLAGS_BUFF_DAZUO = 2	-- 标识是否打坐buff
UNIT_FIELD_FLAGS_GUAJIBAOHU = 3	-- 标识是否是挂机保护
UNIT_FIELD_FLAGS_FACTION_LINGXIU = 4	-- 帮派领袖BUFF
UNIT_FIELD_FLAGS_FACTION_GUWU = 5	-- 帮派鼓舞BUFF
UNIT_FIELD_FLAGS_IS_BOSS_CREATURE = 6	-- 标识是否是副本boss怪
UNIT_FIELD_FLAGS_USE_GAMEOBJECT = 7	-- 标识是否使用游戏对象
UNIT_FIELD_FLAGS_IS_FLZ_PUB_CREATURE = 8	-- 标识是否风流镇酒馆怪
UNIT_FIELD_FLAGS_QUEST_FOLLOW_CREATUR = 9	-- 做任务刷出来的跟谁宠物，任务完成时删掉
PLAYER_SPELL_MAX_COUNT = 10	-- 玩家身上最大技能数
-- 场景服专用的玩家状态下标枚举
PLAYER_SCENED_FLAS_HUNG_UP = 0	-- 挂机状态
PLAYER_SCENED_FLAS_PVP_STATE = 1	-- PVP状态
PLAYER_SCENED_FLAGS_FUBEN_HUNG_UP = 2	-- 标识是否副本连续挂机状态
-- 玩家应用服标志位，玩家选项
PLAYER_APPD_INT_FIELD_FLAGS_IS_ZIBAO = 0	-- 玩家是否自爆
PLAYER_APPD_INT_FIELD_FLAGS_YEYOU_ONLINE = 1	-- 页游是否在线，客户端用的
PLAYER_APPD_INT_FIELD_FLAGS_PHONE_ONLINE = 2	-- 手游是否在线，客户端用的
PLAYER_APPD_INT_FIELD_FLAGS_FROM_KUAFU = 3	-- 玩家是否从pk回到游戏服
PLAYER_APPD_INT_FIELD_FLAGS_GIFT_CREATE = 4	-- 礼包是否已创建
PLAYER_APPD_INT_FIELD_FLAGS_LIMIT_CREATE = 5	-- 限时活动是否已创建
PLAYER_APPD_INT_FIELD_FLAGS_IS_FIRST_RECHARGE = 6	-- 是否已经首充
PLAYER_APPD_INT_FIELD_FLAGS_NEW_PLAYER = 7	-- 是否新玩家，是新玩家则发放礼包等等。。
PLAYER_APPD_INT_FIELD_FLAGS_SAFETY_CODE_CHECK = 8	-- 标识安全码验证是否通过
PLAYER_APPD_INT_FIELD_FLAGS_AUTO_GROUP = 9	-- 玩家是否自动接受组队
PLAYER_APPD_INT_FIELD_FLAGS_IS_HOSTING_LOGIN = 10	-- 是否是托管登录
PLAYER_APPD_INT_FIELD_FLAGS_IS_HOSTING_APPLY = 11	-- 是否托管申请中
PLAYER_APPD_INT_FIELD_FLAGS_SOCIAL_CREATE = 12	-- 社交系统是否以创建	
PLAYER_APPD_INT_FIELD_FLAGS_ITEM_CREATE = 13	-- 物品binlog是否创建
PLAYER_APPD_INT_FIELD_FLAGS_LOGICAL_CREATE = 14	-- 业务逻辑binlog是否创建
-- 基本潜力点属性
QIANLI_TYPE_LILIANG = 0	-- 力量
QIANLI_TYPE_TIZHI = 1	-- 体质
QIANLI_TYPE_SHENFA = 2	-- 身法
QIANLI_TYPE_FANGYU = 3	-- 狂暴
MAX_QIANLI_TYPE = 4
-- 客户端使用的数字下标数量
MAX_CLIENT_UINT32_COUNT = 100
-- 客户端使用的字符串下标数量
MAX_CLIENT_STRING_COUNT = 20
MAX_ITEMS_CD_COUNT = 20	-- 物品大cd最大数量(20个保存时间戳)
MAX_ITEM_USED_COUNT = 5	-- 物品大cd使用次数(5个byte保存次数)
MAX_SPELL_CAPACITY = 20	-- 最多拥有的技能数
-- 技能
SPELL_BASE_LEVEL = 0	-- 技能等级
SPELL_BASE_FORCE = 1	-- 技能等级对应的战斗力
SPELL_BASE_ID = 2	-- 技能ID
MAX_SPELLBASE = 3
-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- 玩家下标
-- //////////////////////////////////////////////////////////////////////////////////////////////////
-- int 部分
-- ////////////////////////////////////////////////////////////////////////
-- 公共部分
PLAYER_FIELD_FD = 0	-- 所在场景服的网络连接号
PLAYER_FIELD_MERGE_DATA_INDEX = 1	-- 玩家合并数据时用来多服务器交互的下标，0.预留，1.回档，2.传送验证数据
PLAYER_FIELD_ENTRY = 2	-- 模板
PLAYER_FIELD_MAP_ID = 3	-- 地图
PLAYER_FIELD_INSTANCE_ID = 4	-- 地图实例
PLAYER_FIELD_POS_X = 5	-- X坐标
PLAYER_FIELD_POS_Y = 6	-- Y坐标
PLAYER_FIELD_ORIENTATION = 7	-- 朝向
PLAYER_FIELD_MOVESPEED = 8	-- 移动速度
PLAYER_FIELD_LEVEL = 10	-- 等级
PLAYER_FIELD_BYTES_0 = 11	-- 四个字节,分别存放 0性别,[1阵营2种族3职业]
PLAYER_FIELD_NPC_FLAG = 12	-- NPC标识
PLAYER_FIELD_DEATH_STATE = 13	-- 生存状态
PLAYER_FIELD_OUT_DAMAGE = 14	-- 外攻
PLAYER_FIELD_IN_DAMAGE = 16	-- 内攻
PLAYER_FIELD_OUT_RESISTANCES = 18	-- 外防
PLAYER_FIELD_IN_RESISTANCES = 20	-- 内防
PLAYER_FIELD_HEALTH = 22	-- 当前生命
PLAYER_FIELD_MAXHEALTH = 24	-- 最大生命
PLAYER_FIELD_COMBAT_HIT = 26	-- 命中
PLAYER_FIELD_COMBAT_EVA = 28	-- 闪避
PLAYER_FIELD_COMBAT_CRIT = 30	-- 暴击
PLAYER_FIELD_COMBAT_CRIT_DEF = 32	-- 抗暴
PLAYER_FIELD_POWERS = 34	-- 能量
PLAYER_FIELD_MAXPOWERS = 38	-- 能量上限
PLAYER_FIELD_COMBAT_RATE = 42	-- 暴击率 / 闪避率(战斗属性百分比)
PLAYER_FIELD_LUCKY = 46	-- 幸运
PLAYER_FIELD_MEILI = 48	-- 魅力
PLAYER_FIELD_BEAR = 50	-- 负重
PLAYER_FIELD_POISON = 52	-- 毒
PLAYER_FIELD_ICE = 54	-- 冰
PLAYER_FIELD_ADD_OUT_DAMAGE = 56	-- 外攻伤害加深 
PLAYER_FIELD_ADD_IN_DAMAGE = 58	-- 内攻伤害加深
PLAYER_FIELD_SUB_OUT_DAMAGE = 60	-- 外攻伤害减免
PLAYER_FIELD_SUB_IN_DAMAGE = 62	-- 内攻伤害减免
PLAYER_FIELD_BUFF = 64	-- BUFF
PLAYER_FIELD_BUFF_RESERVE = 114	-- BUFF保留参数	
PLAYER_INT_FIELD_BUFF_GIVER_UINT_GUID = 164	-- buff giver的uintGuid
PLAYER_INT_FIELD_BUFF_LEVEL_START = 214	-- buff等级 (byte)
PLAYER_INT_FIELD_BUFF_LEVEL_END = 227
PLAYER_FIELD_SKIN = 227	-- 生物变身
PLAYER_FIELD_BYTES_1 = 228	-- 四个字节,分别存放 0怪物分类
PLAYER_FIELD_FORCE = 229	-- 战斗力
PLAYER_FIELD_EQUIPMENT = 231	-- 装备列表，12个32位预留三个
PLAYER_FIELD_CUR_MOUNT = 251	-- 当前坐骑模板id
PLAYER_FIELD_BYTES_2 = 252	-- 玩家标识,存4个byte[0灰名时间 1付费等级 2免费复活 3玩家称号]
PLAYER_FIELD_BYTES_3 = 253	-- 四个字节,分别存放 0头像,[1发型2可用技能槽数量3攻击模式]
PLAYER_FIELD_BYTES_4 = 254	-- 四个字节,分别存放 0坐骑槽数量,1当前骑乘坐骑的坐骑槽位置，未骑乘值为255,2披风格挡等级，3剩余格挡次数
PLAYER_FIELD_BYTES_5 = 255	-- 0 GM权限, 1, 2 
PLAYER_FIELD_AUTO_HP = 256	-- 大红
PLAYER_FIELD_AUTO_MP = 258	-- 大蓝
PLAYER_FIELD_VIP1_TIME_OUT = 260	-- VIP1 超时时间
PLAYER_FIELD_VIP2_TIME_OUT = 261	-- VIP2 超时时间
PLAYER_FIELD_VIP3_TIME_OUT = 262	-- VIP3 超时时间
PLAYER_FIELD_FLAGS = 263	-- 主玩家下标flags
PLAYER_FIELD_FLAGS_END = 271	-- 预留8个32位flags
PLAYER_FIELD_ONLINE_TIME = 271	-- 总在线时长(分钟为单位)
PLAYER_EXPAND_INT_FCM_LOGIN_TIME = 272	-- 防沉迷，单位：分钟	-1是非防沉迷玩家
PLAYER_EXPAND_INT_FCM_LOGOUT_TIME = 273	-- 防沉迷离线时间
PLAYER_EXPAND_INT_CREATE_TIME = 274	-- 角色创建时间
PLAYER_EXPAND_INT_LAST_LOGIN_TIME = 275	-- 最后登录时间
PLAYER_EXPAND_INT_LAST_LOGOUT_TIME = 276	-- 最后离线时间
PLAYER_EXPAND_INT_NUMBER_OF_LOGINS = 277	-- 累积登录次数
PLAYER_EXPAND_INT_MONEY = 278	-- 各种货币
PLAYER_EXPAND_INT_USE_FASHION = 302	-- 是否启用时装,目前用到20个pos
PLAYER_EXPAND_INT_XP = 303	-- 当前经验，32位
PLAYER_EXPAND_INT_NEXT_LEVEL_XP = 305	-- 下一级经验，32位
PLAYER_EXPAND_INT_MAP_STATUS = 307	-- 地图开启进度
PLAYER_EXPAND_INT_GAG_END_TIME = 308	-- 禁言结束时间
PLAYER_EXPAND_INT_TO_MAP = 309	-- 玩家要传送到的地图
PLAYER_EXPAND_INT_TO_INSTANCE_ID = 310	-- 玩家要传送到的地图实例ID
PLAYER_EXPAND_INT_TO_POS_X = 311	-- 玩家药传送到的坐标
PLAYER_EXPAND_INT_TO_POS_Y = 312
PLAYER_EXPAND_INT_TO_LINE_NO = 313	-- 传送线号
PLAYER_EXPAND_INT_DB_MAP = 314	-- 玩家最后一次进入副本前的地图	
PLAYER_EXPAND_INT_DB_POS_X = 315	-- 玩家最后一次进入副本前的坐标
PLAYER_EXPAND_INT_DB_POS_Y = 316
PLAYER_EXPAND_INT_CLIENT_DATA = 317	-- 远程存储
-- ////////////////////////////////////////////////////////////////////////
-- 应用服部分	
PLAYER_APPD_INT_FIELD_FLAG = 417	-- 玩家标志位
PLAYER_APPD_INT_FIELD_FLAG_END = 424	-- 结束下标
PLAYER_APPD_INT_FIELD_DAILY_TIME = 424	-- 每天在线时长（min）
PLAYER_APPD_INT_FIELD_RESET_DALIY = 425	-- 重置的时间点每小时一次
PLAYER_APPD_INT_FIELD_RECHARGE_SUM = 449	-- 累计充值总数
PLAYER_APPD_INT_FIELD_LAST_RECHARGE_TIME = 450	-- 最后一笔充值时间
PLAYER_APPD_INT_FLELD_JHM_FLAGS = 451	-- 激活码flags
PLAYER_APPD_INT_FLELD_JHM_FLAGS_END = 459	-- 激活码flags_end
-- 主背包扩展时间戳
PLAYER_APPD_INT_FIELD_EXTENSION_END_TIME = 460	-- 主包裹扩展结束时间戳
PLAYER_APPD_INT_FIELD_EXTENSION_REMAIN_TIME = 461	-- 主包裹扩展剩余多少时间
PLAYER_APPD_INT_FIELD_END = 900
-- 场景服扩展下标开始了
PLAYER_SCENED_INT_FLAGS = 901	-- 玩家场景服标志位
-- 任务槽信息
PLAYER_SCENED_INT_FIELD_QUEST_LOG_0 = 909
PLAYER_SCENED_INT_FIELD_UNKNOW_QUEST = 1165
PLAYER_SCENED_INT_FIELD_QUEST_ITEMS = 1167
PLAYER_SCENED_INT_FIELD_QUEST_COMPLETE_LIST = 1177	-- 完成列表（任务id对应的bit为1时说明已经完成）
-- 技能槽信息
PLAYER_SCENED_INT_FIELD_SLOT_SPELL_0 = 1377
PLAYER_SCENED_INT_FIELD_SLOT_SPELL_END = 1407	-- 技能结束的地方
-- 被动技能
PLAYER_INT_FIELD_PASSIVE_SPELL = 1407
PLAYER_INT_FIELD_PASSIVE_SPELL_END = 1467
PLAYER_EXPAND_KILL_MONSTER = 1467	-- 杀怪数
-- 跨服
PLAYER_APPD_INT_FIELD_KUAFU_WARID = 1468	-- 跨服场次id
PLAYER_INT_FIELD_KUAFU_NUMBER = 1469	-- 0:玩家报名跨服时收到匹配信息中给的编号 1:跨服类型（值参照枚举：EKUAFU_TYPE）
PLAYER_HT_INT_FIELD_MAIN_QUEST_ID = 1470	-- 当前主线任务
-- ////////////////////////////////////////////////////////////////////////////////////////////////////////
-- 字符串部分
PLAYER_STRING_FIELD_ACCOUNT = 4	-- 账号
PLAYER_STRING_FIELD_TELEPORT_GUID = 5	-- 传送GUID
PLAYER_APPD_STRING_FIELD_CLIENT_DATA = 6	-- 远程存储
PLAYER_STRING_FIELD_LAST_LOGIN_IP = 26	-- 玩家最后登录的IP
PLAYER_STRING_FIELD_RECHARGE_ID = 27	-- 最后充值ID
PLAYER_STRING_FIELD_CREATE_LOGIN_IP = 28	-- 玩家创建IP
PLAYER_APPD_STRING_FIELD_PINGTAI_INFO = 29	-- 平台信息
PLAYER_STRING_FIELD_DB_KUAFU_INFO = 30	-- 玩家跨服信息,是否为跨服玩家依据这个下标是不是空串
PLAYER_STRING_FIELD_FACTION_GUID = 31	-- 帮派guid
-- 游戏配置专用的状态下标枚举
GAME_CONFIG_FIELD_FLAGS_SHOW_PLATFORM_NAME = 0	-- 是否显示平台名
GAME_CONFIG_FIELD_FLAGS_SHOW_SERVER_ID = 1	-- 是否显示服务器ID
GAME_CONFIG_FIELD_FLAGS_SHOW_POST = 2	-- 聊天是否post
-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- 游戏配置
GAME_CONFIG_INT_FIELD_KAIFUSHIJIAN = 0	-- 开服时间
GAME_CONFIG_INT_FIELD_FLAGS = 1	-- 游戏配置标志位
GAME_CONFIG_INT_FIELD_ADDTIME = 9	-- 合服时间
GAME_CONFIG_INT_FIELD_WORLD_SVR_TYPE = 10	-- 服务器类型(见枚举: ESERVER_TYPE)
GAME_CONFIG_STRING_FIELD_PLATFORM_ID = 4	-- 平台ID
GAME_CONFIG_STRING_FIELD_GM_QQ = 5	-- GM和QQ
GAME_CONFIG_STRING_FIELD_DB_CONN = 6	-- 数据库连接串
GAME_CONFIG_STRING_FIELD_LOGIN_KEY = 7	-- 登录秘钥
GAME_CONFIG_STRING_FIELD_LOG_DB_CONN = 8	-- 日志数据库连接串
GAME_CONFIG_STRING_LOCAL_HDD_PATH = 9	-- 本地硬盘数据保存地址
GAME_CONFIG_STRING_EXT_WEB_INTERFACE = 10	-- web接口配置
GAME_CONFIG_STRING_CONF_SVR_URL = 11	-- 配置服url地址
GAME_CONFIG_STRING_WORLD_SERVER_URL = 12	-- 世界服url地址
GAME_CONFIG_STRING_FIELD_SERVER = 200	-- 原始服务器
GAME_CONFIG_STRING_FIELD_SERVER_LIST_BEGIN = 201	-- 服务器列表
-- 客户端模块枚举
CLIENT_MODULE_CENTER = 0	-- 中心模块
CLIENT_MODULE_CREATE = 1	-- 创建角色模块
CLIENT_MODULE_SCENE = 2	-- 场景模块
CLIENT_MODULE_UI = 3	-- UI模块
CLIENT_MODULE_SH = 4	-- 梭哈模块
MAX_CLIENT_MODULE = 5
-- 客户端模块版本信息
CLIENT_VERSION_INT_CREATE_TIME = 0	-- 版本创建时间
MAX_CLIENT_VERSION_INT = 1
CLIENT_VERSION_STRING_VERSIONS = 0	-- 模块版本号
CLIENT_VERSION_STRING_COMMENT = 1	-- 模块版本说明
MAX_CLIENT_VERSION_STRING = 2
-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- 客户端配置信息
CLIENT_CONFIG_INT_FIELD_MODULE_INFO_BEGIN = 0
CLIENT_CONFIG_INT_FIELD_MODULE_INFO_END = 5
CLIENT_CONFIG_STRING_FIELD_MODULE_INFO_BEGIN = 4
CLIENT_CONFIG_STRING_FIELD_MODULE_INFO_END = 14
-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- 世界变量
GLOBALVALUE_INT_FIELD_FLAGS = 0	-- 世界变量标志位
GLOBALVALUE_INT_FIELD_LIMIT_ACTIVITY_VERSION = 8	-- 活动版本号
GLOBALVALUE_INT_FIELD_LIMIT_ACTIVITY_END_TIME = 9	-- 活动结束时间
GLOBALVALUE_INT_FIELD_LIMIT_ACTIVITY_ITEM = 10	-- 活动物品配置
GLOBALVALUE_INT_FIELD_LIMIT_ACTIVITY_ITEM_END = 40	-- 最多10个道具掉落	
GLOBALVALUE_INT_FIELD_ONLINE_PLAYER_NUM = 40	-- 计录全服在线玩家数
GLOBALVALUE_INT_FIELD_WORLD_CONNECTION_STATUS = 41	-- 世界服连接状态
GLOBALVALUE_STRING_FIELD_LIMIT_ACTIVITY_SCRIPT = 4	-- 限时活动类名
-- 计时器世界变量计数器
GLOBALCOUNTER_INT_FIELD_ONLINE_AWARD_COUNT = 0	-- 全服银子数量
GLOBALCOUNTER_INT_FIELD_DAILY_ADD_BIND_GOLD = 2	-- 每日新增绑定元宝数量
GLOBALCOUNTER_INT_FIELD_DAILY_SUB_BIND_GOLD = 4	-- 每日消耗绑定元宝数量
GLOBALCOUNTER_INT_FIELD_DAILY_ADD_GOLD_INGOT = 6	-- 每日新增元宝数量
GLOBALCOUNTER_INT_FIELD_DAILY_SUB_GOLD_INGOT = 8	-- 每日消耗元宝数量
GLOBALCOUNTER_INT_FIELD_DAILY_ADD_SILVER = 10	-- 每日新增银子数量
GLOBALCOUNTER_INT_FIELD_DAILY_SUB_SILVER = 12	-- 每日消耗银子数量
MAX_GLOBALCOUNTER_INT_FIELD = 13
-- //////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- 地图
MAP_INT_FIELD_MAP_ID = 0	-- 地图模板ID
MAP_INT_FIELD_INSTANCE_ID = 1	-- 实例ID
MAP_INT_FIELD_LINE_NO = 2	-- 分线ID
MAP_INT_FIELD_WARID = 2	-- 场次id
MAP_INT_FIELD_KUAFU_TYPE = 3	-- 跨服类型
MAP_INT_FIELD_STATE = 4	-- 0.地图大状态,1.地图小状态,2.地图自动复活时间,3预留状态
MAP_INT_FIELD_KILL_NUM = 5	-- 杀怪数
MAP_INT_FIELD_CREATE_TM = 6	-- 副本创建时间
MAP_INT_FIELD_END_TM = 7	-- 副本结束时间
MAP_INT_FIELD_INSTANCE_TYPE = 8	-- 副本类型
-- 地图字符串部分
MAP_STR_GENERAL_ID = 4
--  桃花迷阵最大刷新次数
TAOHUA_REFRESH_TIMES = 10
-- 桃花迷阵地图数据
TAOHUA_INT_FIELD_REFRESH_TIMES = 9	-- 桃花迷阵已经刷新次数
TAOHUA_INT_FIELD_BOSS_CURR_HP = 10	-- BOSS当前血量
TAOHUA_STR_FIELD_REAL_BOSS_GUID = 5	-- BOSS真身GUID
-- 塔的最大层数
TOWER_MAX_FLOOR = 2
-- 塔怪每层击杀数量
TAGUAI_INT_FIELD_FIRST_FLOOR = 9	-- 第一层的信息
-- 战斗信息整形字段枚举
FIGHTING_INFO_INT_VALUES = 0	-- 伤害或者治疗 治疗发负数
FIGHTING_INFO_INT_UINT8 = 2	-- 0:是否被杀 1:施法者生物类型（玩家还是生物）2:目标生物类型（玩家还是生物） 3:伤害类型(暴击、闪避之类的)
FIGHTING_INFO_INT_SPELL_ID = 3	-- 技能id
FIGHTING_INFO_INT_HP = 4	-- 技能计算完以后，生物剩余血量
FIGHTING_INFO_INT_RESERVE_0 = 5	-- 预留
FIGHTING_INFO_INT_RESERVE_1 = 6	-- 预留	
FIGHTING_INFO_INT_RESERVE_2 = 7	-- 预留
FIGHTING_INFO_INT_RESERVE_3 = 8	-- 预留	
MAX_FIGHTING_INFO_INT = 9
-- 战斗信息整形字符型枚举
-- 貌似没必要,随便留一个吧
FIGHTING_INFO_STRING_CASTER = 0	-- 施法者
FIGHTING_INFO_STRING_TARGET = 1	-- 目标
MAX_FIGHTING_INFO_STRING = 2
-- 战斗信息最大数量
MAX_FIGHTING_INFO_COUNT = 100
-- 战斗信息字段
MAX_FIGHTING_INFO_INT_NOW_INDEX = 0	-- 当前战斗力信息下标用到第几个战斗信息了
MAX_FIGHTING_INFO_INT_START = 1
MAX_FIGHTING_INFO_INT_FIELD = 901
FIGHTING_INFO_STRING_FIELD_START = 4
MAX_FIGHTING_INFO_STRING_FIELD = 204
-- 查询用的玩家信息binlog
QUERY_PLAYER_INT_UINT16 = 0	-- 0 等级，1 宝石等级
QUERY_PLAYER_INT_BYTE1 = 1	-- 0 头像，1 发型，2 种族，3 性别
QUERY_PLAYER_INT_BYTE2 = 2	-- 0 阵营，1 是否在线，2 称号,3 vip
--  基础属性
QUERY_PLAYER_INT_BASE_ATTR_START = 3	-- 玩家基本属性开始
QUERY_PLAYER_INT_BASE_ATTR_END = 21	-- 玩家基本属性结束
QUERY_PLAYER_INT_FIXED_ATTR_START = 21	-- 玩家固定属性开始
QUERY_PLAYER_INT_FIXED_ATTR_END = 39	-- 玩家固定属性结束	
QUERY_PLAYER_INT_LUCKY = 39	-- 幸运
QUERY_PLAYER_INT_MEILI = 41	-- 魅力
QUERY_PLAYER_INT_BEAR = 43	-- 负重
QUERY_PLAYER_INT_POISON = 45	-- 毒
QUERY_PLAYER_INT_ICE = 47	-- 冰
QUERY_PLAYER_MOVESPEED = 49	-- 移动速度
QUERY_PLAYER_PHYSICAL = 51	-- 体力
QUERY_PLAYER_INT_FORCE = 53	-- 战斗力
QUERY_PLAYER_ONLINE_TIME = 55	-- 总在线时长
--  身上的装备
QUERY_PLAYER_INT_EQUIPMENT = 56
QUERY_PLAYER_INT_EQUIPMENT_END = 76
QUERY_PLAYER_INT_FLAG = 76	-- 查询某些标志位
QUERY_PLAYER_INT_FORCE_LEVEL = 77	-- 等级战斗力PLAYER_INT_PIFENG_ZIZHI_FORCE
QUERY_PLAYER_INT_FORCE_ITEM = 79	-- 装备战斗力
QUERY_PLAYER_INT_FORCE_FACTION = 81	-- 帮派战斗力
QUERY_PLAYER_INT_FLAG_TYPE = 83	-- 当前玩家查询类型标志
QUERY_PLAYER_INT_FORGING_STRENG = 84	-- 0 查询玩家强化等级，1 预留 16位
QUERY_PLAYER_STRING_GUID = 4	-- 不要直接放到guid去，怕混乱
QUERY_PLAYER_STRING_NAME = 5	-- 玩家名字
QUERY_PLAYER_STRING_FACTION_ID = 6	-- 帮派ID
QUERY_PLAYER_STRING_FACTION_NAME = 7	-- 帮派名称
MAX_QUERY_PLAYER_STRING_FIELD = 8
-- ///////////////////////////////////查看物品//////////////////////////////////////////////////////////////////////////
-- 查看物品下标
-- //////////////////int部分///////////////////////////////////////
ITEM_QUERY_INT_FIELD_COUNT = 0
-- //////////////////string部分///////////////////////////////////////
ITEM_QUERY_STR_FIELD_START = 4
-- 礼包信息记录类型枚举
GIFTPACKS_INFO_INT_ID = 0	-- 礼包ID
GIFTPACKS_INFO_INT_START_TIME = 1	-- 发放时间
GIFTPACKS_INFO_INT_END_TIME = 2	-- 结束时间
GIFTPACKS_INFO_INT_BYTE = 3	-- 0,礼包类型，1，领取状态,2 已阅读,3是否删除
MAX_GIFTPACKS_INFO_INT = 4
GIFTPACKS_INFO_STRING_GIFT_NAME = 0	-- 礼包名称
GIFTPACKS_INFO_STRING_GIFT_DESC = 1	-- 礼包说明
GIFTPACKS_INFO_STRING_GIFT_FROM = 2	-- 礼包出处，当玩家赠送时填写玩家名字，默认为空，系统赠送
GIFTPACKS_INFO_STRING_GIFT_ITEM = 3	-- 礼包物品集合
MAX_GIFTPACKS_INFO_STRING = 4
-- 礼包信息最多条数
MAX_GIFTPACKS_INFO_COUNT = 300
-- 礼包信息binlog
MAX_GIFTPACKS_INFO_INT_NOW_INDEX = 0	-- 当前礼包信息下标索引
GIFTPACKS_INT_FIELD_BEGIN = 1
MAX_GIFTPACKS_INT_FIELD = 1201
GIFTPACKS_STRING_FIELD_BEGIN = 4
MAX_GIFTPACKS_STRING_FIELD = 1204
-- 排行类型
RANK_TYPE_POWER = 0	-- 战斗力排行
RANK_TYPE_LEVEL = 1	-- 等级排行
RANK_TYPE_MONEY = 2	-- 财富排行
RANK_TYPE_ONLINE_TIME = 3	-- 在线时长排行
MAX_RANK_TYPE = 4
-- 单个排行榜最大排名个数
RANK_LIST_MAX_VALUES = 110
-- 排行榜个体binlog下标
RANK_LIST_CURRENT_OBJ_INT_FIELD_TYPE = 0	-- 排行榜类型
RANK_LIST_CURRENT_OBJ_INT_FIELD_RANKING = 1	-- 名次
RANK_LIST_CURRENT_OBJ_INT_FIELD_BYTE = 2	-- byte 0，性别
-- 排行榜
RANK_LIST_CURRENT_OBJ_INT_FIELD_FORCE = 3	-- 战斗力
RANK_LIST_CURRENT_OBJ_INT_FIELD_LEVEL = 5	-- 等级
RANK_LIST_CURRENT_OBJ_INT_FIELD_MONEY = 6	-- 铜钱
RANK_LIST_CURRENT_OBJ_INT_FIELD_ONLINE_TIME = 8	-- 在线时长
RANK_LIST_CURRENT_OBJ_STR_FIELD_GUID = 4
RANK_LIST_CURRENT_OBJ_STR_FIELD_PLAYER_GUID = 5	-- 玩家guid
RANK_LIST_CURRENT_OBJ_STR_FIELD_PLAYER_NAME = 6	-- 玩家名字
RANK_LIST_CURRENT_OBJ_STR_FIELD_FACTION_NAME = 7	-- 帮派名字
-- 弹窗公告记录类型枚举
RIGHTFLOAT_INFO_INT_ID = 0	-- 公告ID
RIGHTFLOAT_INFO_INT_START_TIME = 1	-- 起始时间
RIGHTFLOAT_INFO_INT_END_TIME = 2	-- 结束时间
RIGHTFLOAT_INFO_INT_ZONE_1 = 3	-- 0-7点
RIGHTFLOAT_INFO_INT_ZONE_2 = 4	-- 8-13点
RIGHTFLOAT_INFO_INT_ZONE_3 = 5	-- 14-23点
RIGHTFLOAT_INFO_INT_BYTE = 6	-- 0 弹窗设置,1 公告状态,2 预留,3 预留
RIGHTFLOAT_INFO_INT_ADD_TIME = 7	-- 添加时间
MAX_RIGHTFLOAT_INFO_INT = 8
RIGHTFLOAT_INFO_STRING_SUBJECT = 0	-- 标题
RIGHTFLOAT_INFO_STRING_CONTENT = 1	-- 内容
RIGHTFLOAT_INFO_STRING_LINK = 2	-- 链接地址
MAX_RIGHTFLOAT_INFO_STRING = 3
-- 弹窗信息最多条数
MAX_RIGHTFLOAT_INFO_COUNT = 100
-- 弹窗公告信息binlog
MAX_RIGHTFLOAT_INFO_INT_NOW_INDEX = 0	-- 当前弹窗公告信息下标索引
RIGHTFLOAT_INT_FIELD_START = 1
MAX_RIGHTFLOAT_INT_FIELD = 801
RIGHTFLOAT_STRING_FIELD_START = 4
MAX_RIGHTFLOAT_STRING_FIELD = 304
-- 限时活动binlog
LIMIT_ACTIVITY_INT_FIELD_VERSION = 0	-- 活动版本号
LIMIT_ACTIVITY_INT_FIELD_START_TIME = 1	-- 活动开始时间
LIMIT_ACTIVITY_INT_FIELD_END_TIME = 2	-- 活动结束时间
LIMIT_ACTIVITY_INT_FIELD_RECHARGE_SUM = 3	-- 充值总数
LIMIT_ACTIVITY_INT_FIELD_RECHARGE_TIME = 4	-- 最后充值时间
LIMIT_ACTIVITY_INT_FIELD_REWARD_COUNT = 100	-- 活动领取计数开始
LIMIT_ACTIVITY_INT_FIELD_REWARD_COUNT_END = 500	-- 活动领取计数结束
LIMIT_ACTIVITY_STRING_FIELD_RECHARGE_ID = 4	-- 最后充值ID
LIMIT_ACTIVITY_STRING_FIELD_CLIENT_CONFIG = 5	-- 客户端配置
-- 公告信息最多条数
MAX_NOTICE_MESSAGE_NUMBER = 100
-- 公告信息类型
NOTICE_MESSAGE_INFO_TYPE_FISHING = 0	-- 钓鱼公告
NOTICE_MESSAGE_INFO_TYPE_MINING = 1	-- 矿洞公告
NOTICE_MESSAGE_INFO_TYPE_WORLD_BOSS = 2	-- 世界boss掉落
NOTICE_MESSAGE_INFO_TYPE_KAIFUJIJIN = 3	-- 开服基金公告
MAX_MESSAGE_INFO_TYPE = 4
-- 公告信息binlog
NOTICE_MESSAGE_INT_FIELD_INDEX = 0	-- 公告位置索引
NOTICE_MESSAGE_INT_FIELD_INDEX_END = 4	-- 公告索引位置结束
NOTICE_MESSAGE_STRING_FIELD_START = 4	-- 公告信息内容开始
NOTICH_MESSAGE_STRING_FIELD_END = 404	-- 公告信息内容结束
-- 托管操作
HOSTING_OPT_TYPE_APPLY = 0	-- 托管申请
HOSTING_OPT_TYPE_AGREED = 1	-- 托管同意
HOSTING_OPT_TYPE_CANCEL = 2	-- 托管取消
HOSTING_OPT_TYPE_LOGIN = 3	-- 托管登录
HOSTING_OPT_TYPE_REFUSE = 4	-- 托管拒绝
HOSTING_OPT_TYPE_DUE_TO = 5	-- 托管到期
HOSTING_OPT_TYPE_APPLY_DUE_TO = 6	-- 托管申请到期
-- 部位信息个数
MAX_EQUIP_PART_NUMBER = 10
-- 一个部位的宝石个数
ONE_EQUIP_PART_GEM_NUMBER = 6
--  一个装备部位信息类型
EQUIP_PART_OPT_TYPE_STRENGTH_LEVEL_OFFSET = 0	-- 强化等级偏移值
EQUIP_PART_OPT_TYPE_GEM_INFO_OFFSET = 1	-- 宝石信息偏移值
EQUIP_PART_OPT_TYPE_GEM_LEVEL_OFFSET = 0	-- 宝石信息中宝石等级偏移值
EQUIP_PART_OPT_TYPE_GEM_EXP_OFFSET = 1	-- 宝石信息中宝石经验偏移值
EQUIP_PART_OPT_TYPE_ONE_GEM_INFO_LENGTH = 2	-- 一个宝石信息的长度
EQUIP_PART_OPT_TYPE_ONE_PART_INFO_LENGTH = 13	-- 一个装备部位的信息长度
EQUIP_PART_OPT_TYPE_PARTS_INFO_LENGTH = 130	-- 所有装备部位总信息长度 
--  业务BinLog
APPD_LOGICAL_INFO_INT_FIELD_STRENGTH_START = 0	-- 部位信息的起始位置
APPD_LOGICAL_INFO_INT_FIELD_STRENGTH_END_EXCLUDE = 130	-- 装备部位的边界
FACTION_INT_FIELD_LEVEL = 0	-- 帮派等级
