AbstractQuest = require("appd.quest.AbstractQuest")
require("appd.quest.QuestPlayerLevel")
require("appd.quest.QuestPlayerForce")
require("appd.quest.QuestJoinFaction")
require("appd.quest.QuestFactionDonate")
require("appd.quest.QuestJoinFactionActivity")
require("appd.quest.QuestJoinFieldBoss")
require("appd.quest.QuestJoinWorldBoss")
require("appd.quest.QuestJoinResourceInstance")
require("appd.quest.QuestJoinTrialInstance")
require("appd.quest.QuestOwnDivine")
require("appd.quest.QuestEquipDivine")
require("appd.quest.QuestStrengthDivine")
require("appd.quest.QuestRaiseSkill")
require("appd.quest.QuestTrainMount")
require("appd.quest.QuestRaiseMountSkill")
require("appd.quest.QuestFriendDonate")
require("appd.quest.QuestStrengthSuit")
require("appd.quest.QuestRaiseGem")
require("appd.quest.QuestNPCTalk")
require("appd.quest.QuestPick")
require("appd.quest.QuestInspect")
require("appd.quest.QuestKillMonster")
require("appd.quest.QuestUseItem")

-- 这个一定要放到最后
require("appd.quest.QuestManager")